window.catalogProducts = [
  {
    "id": "d1",
    "source": "digitalpc",
    "name": "ASUS VIVOBOOK GO 14 E410KA-CL4128",
    "specs": "Intel Celeron N4500 8gb RAM 128gb SSD 14″ FHD W11",
    "price": 355.0,
    "image": "imagenes/01-asus-vivobook-go-14-e410ka-cl4128.png",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/09/PORTADA.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivobook-go-14-e410ka-cl4128-intel-celeron-n4500-8gb-ram-128gb-ssd-14-fhd-w11/",
    "badge": "#1 más económico"
  },
  {
    "id": "d2",
    "source": "digitalpc",
    "name": "ASUS VIVOBOOK 14 X1404VA",
    "specs": "Intel Core I3-1315U 8gb RAM 128gb SSD 14″ W11 $ 45 · intel-core-i3-1315u-8gb-ram-128gb-ssd-14-w11-2",
    "price": 455.0,
    "image": "imagenes/02-asus-vivobook-14-x1404va.png",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/07/descarga-7.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivobook-14-x1404va-intel-core-i3-1315u-8gb-ram-128gb-ssd-14-w11-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "d3",
    "source": "digitalpc",
    "name": "HP 15-FD0130WM",
    "specs": "Intel Core I3-N305 8gb RAM 256gb SSD 15.6″ W11 $ 4 · intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11",
    "price": 499.0,
    "image": "imagenes/03-hp-15-fd0130wm.png",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/09/HP1-3.png",
    "url": "https://digitalpcecuador.com/producto/hp-15-fd0130wm-intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d4",
    "source": "digitalpc",
    "name": "HP 15-FD0133WM",
    "specs": "Intel Core I3-N305 8gb RAM 256gb SSD 15.6″ W11 $ 4 · intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11",
    "price": 499.0,
    "image": "imagenes/04-hp-15-fd0133wm.png",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/09/HP1-3.png",
    "url": "https://digitalpcecuador.com/producto/hp-15-fd0133wm-intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d5",
    "source": "digitalpc",
    "name": "ASUS VIVIBOOK GO 15 E1504GA",
    "specs": "Intel Core I3-N305 8gb RAM 256gb SSD 15.6″ W11 $ 5 · intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11",
    "price": 545.0,
    "image": "imagenes/05-asus-vivibook-go-15-e1504ga.png",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/07/descarga-8.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivibook-go-15-e1504ga-intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d6",
    "source": "digitalpc",
    "name": "ASUS VIVOBOOK GO 15 E1504FA",
    "specs": "AMD Ryzen 5-7520U 8gb RAM 512gb SSD 15.6″ W11 $ · amd-ryzen-5-7520u-8gb-ram-512gb-ssd-15-6-w11-3",
    "price": 545.0,
    "image": "imagenes/06-asus-vivobook-go-15-e1504fa.png",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2024/12/descarga-8.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivobook-go-15-e1504fa-amd-ryzen-5-7520u-8gb-ram-512gb-ssd-15-6-w11-3/",
    "badge": "Precio bajo"
  },
  {
    "id": "d7",
    "source": "digitalpc",
    "name": "ASUS VIVOBOOK 14 X1404VAP",
    "specs": "Intel Core 5-120U 8gb RAM 256gb SSD 14″ W11 $ 575 · intel-core-5-120u-8gb-ram-256gb-ssd-14-w11",
    "price": 575.0,
    "image": "imagenes/07-asus-vivobook-14-x1404vap.png",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/08/descarga-4-2.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivobook-14-x1404vap-intel-core-5-120u-8gb-ram-256gb-ssd-14-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d8",
    "source": "digitalpc",
    "name": "HP 15-fc0256la",
    "specs": "AMD Ryzen 5-7520U 16gb RAM 512gb SSD 15.6″ $ 655 · amd-ryzen-5-7520u-16gb-ram-512gb-ssd-15-6",
    "price": 655.0,
    "image": "imagenes/08-hp-15-fc0256la.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/09/FOTOS-WEB.jpg",
    "url": "https://digitalpcecuador.com/producto/hp-15-fc0256la-amd-ryzen-5-7520u-16gb-ram-512gb-ssd-15-6/",
    "badge": "Precio bajo"
  },
  {
    "id": "d9",
    "source": "digitalpc",
    "name": "LENOVO IDEAPAD 1",
    "specs": "Intel Core I5-1335U 16gb RAM 256gb SSD 15.6” W11 $",
    "price": 675.0,
    "image": "imagenes/09-lenovo-ideapad-1.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/06/FOTOS-WEB-27.jpg",
    "url": "https://digitalpcecuador.com/producto/lenovo-ideapad-1-intel-core-i5-1335u-16gb-ram-256gb-ssd-15-6-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d10",
    "source": "digitalpc",
    "name": "ASUS VIVOBOOK GO 15 E1504FA",
    "specs": "ASUS VIVOBOOK GO 15 E1504FA RYZEN 5-40 16GB 512SSD 15,6´´ FHD $ 675.00 · RYZEN 5-40 16GB 512SSD 15 · ryzen-5-4016gb512ssd156fhd",
    "price": 675.0,
    "image": "imagenes/10-asus-vivobook-go-15-e1504fa.png",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/07/PORTADA-2.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivobook-go-15-e1504fa-ryzen-5-4016gb512ssd156fhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "m1",
    "source": "mundotek",
    "name": "Infinix SMART 6 HD",
    "specs": "2GB · 32GB",
    "price": 69.0,
    "image": "imagenes/11-infinix-smart-6-hd.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/infinix-smart-6-hd-azul.webp",
    "url": "https://mundotek.com.ec/producto/infinix-smart-6-hd-ram-2gb-32gb/",
    "badge": "#1 más económico"
  },
  {
    "id": "m2",
    "source": "mundotek",
    "name": "ZTE Blade A35e",
    "specs": "2GB · 64GB · 42gb",
    "price": 89.0,
    "image": "imagenes/12-zte-blade-a35e.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/zte_blade_a35e.webp",
    "url": "https://mundotek.com.ec/producto/zte-blade-a35e-ram-42gb-64gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m3",
    "source": "mundotek",
    "name": "Xiaomi 15 Ultra",
    "specs": "Kit fotográfico",
    "price": 99.0,
    "image": "imagenes/13-xiaomi-15-ultra.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/kit15.webp",
    "url": "https://mundotek.com.ec/producto/kit-fotografico-del-xiaomi-15-ultra/",
    "badge": "Precio bajo"
  },
  {
    "id": "m4",
    "source": "mundotek",
    "name": "Realme C21Y Ram4GB/64GB",
    "specs": "4GB · 64GB",
    "price": 99.0,
    "image": "imagenes/14-realme-c21y-ram4gb-64gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/rmc21y-464gb-blu-9-1000x1000-1.jpg",
    "url": "https://mundotek.com.ec/producto/realme-c21y-ram4gb-64gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m5",
    "source": "mundotek",
    "name": "Realme C11 (2021)",
    "specs": "Peso: 0.19 kg · 2GB · 32GB",
    "price": 102.0,
    "image": "imagenes/15-realme-c11-2021.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/07/Realme-C11.jpg",
    "url": "https://mundotek.com.ec/producto/realme-c11/",
    "badge": "Precio bajo"
  },
  {
    "id": "m6",
    "source": "mundotek",
    "name": "Infinix Hot 20i",
    "specs": "3 GB · 128GB",
    "price": 129.0,
    "image": "imagenes/16-infinix-hot-20i.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/hot-20i.webp",
    "url": "https://mundotek.com.ec/producto/infinix-hot-20i-ram-43-gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m7",
    "source": "mundotek",
    "name": "Samsung A07",
    "specs": "4GB · 128GB",
    "price": 135.0,
    "image": "imagenes/17-samsung-a07.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/a07.webp",
    "url": "https://mundotek.com.ec/producto/samsung-a07-ram-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m8",
    "source": "mundotek",
    "name": "Tecno Spark Go 3 Ram4+4GB-128GB",
    "specs": "Almacenamiento: 128GB , 64GB · 4GB · 128GB · 44gb · 64gb",
    "price": 135.0,
    "image": "imagenes/18-tecno-spark-go-3-ram4-4gb-128gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/tecno-spark-go-3.webp",
    "url": "https://mundotek.com.ec/producto/tecno-spark-go-3-ram44gb-64gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m9",
    "source": "mundotek",
    "name": "Honor Play 10 ram4+4 GB-128GB",
    "specs": "4 GB · 128GB",
    "price": 135.0,
    "image": "imagenes/19-honor-play-10-ram4-4-gb-128gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/07/honor-play-10.jpg",
    "url": "https://mundotek.com.ec/producto/honor-play-10-ram44-gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m10",
    "source": "mundotek",
    "name": "Xiaomi Redmi A7 Pro",
    "specs": "4GB · 128GB",
    "price": 135.0,
    "image": "imagenes/20-xiaomi-redmi-a7-pro.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/xiaomi-redmi-a7-pro.webp",
    "url": "https://mundotek.com.ec/producto/xiaomi-redmi-a7-pro-ram-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m11",
    "source": "mundotek",
    "name": "LOGIC G1L GAMING PHONE+GAME PAD+BUDS",
    "specs": "128GB · 10GB · 410gb",
    "price": 139.0,
    "image": "imagenes/21-logic-g1l-gaming-phone-game-pad-buds.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/08/logi.png",
    "url": "https://mundotek.com.ec/producto/logic-g1l-gaming-phonegame-padbuds-ram-410gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m12",
    "source": "mundotek",
    "name": "Infinix smart 20",
    "specs": "Procesador: MediaTek Helio G81 Ultra · Memoria RAM: 4+4 GB · Capacidad de almacenamiento: 128GB , 64GB · Almacenamiento: 128GB , 256GB , 64GB · Pantalla: 6.78¨ · Resolución de pantalla: 720 x 1600 píxeles",
    "price": 139.0,
    "image": "imagenes/22-infinix-smart-20.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/infinix-smart-20.jpg",
    "url": "https://mundotek.com.ec/producto/infinix-smart-20-ram-4-4-gb-64gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m13",
    "source": "mundotek",
    "name": "MOTOROLA G06",
    "specs": "4GB · 256GB",
    "price": 149.0,
    "image": "imagenes/23-motorola-g06.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/g06.jpeg",
    "url": "https://mundotek.com.ec/producto/motorola-g06-ram-4gb4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m14",
    "source": "mundotek",
    "name": "TCL L10+",
    "specs": "Peso: 0.17 kg",
    "price": 150.0,
    "image": "imagenes/24-tcl-l10.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/04/1062.jpg",
    "url": "https://mundotek.com.ec/producto/l10/",
    "badge": "Precio bajo"
  },
  {
    "id": "m15",
    "source": "mundotek",
    "name": "Honor X5c Plus",
    "specs": "4GB · 256GB",
    "price": 155.0,
    "image": "imagenes/25-honor-x5c-plus.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/x5plus.jpg",
    "url": "https://mundotek.com.ec/producto/honor-x5c-plus-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m16",
    "source": "mundotek",
    "name": "Telefono Tecno Spark 30C",
    "specs": "Memoria Ram: 4GB , 8GB · 4GB · 256GB",
    "price": 159.0,
    "image": "imagenes/26-telefono-tecno-spark-30c.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/11/spark30c.webp",
    "url": "https://mundotek.com.ec/producto/telefono-tecno-spark-30c-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m17",
    "source": "mundotek",
    "name": "OPPO A5 4G",
    "specs": "4GB · 256GB",
    "price": 165.0,
    "image": "imagenes/27-oppo-a5-4g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/a5-4g.png",
    "url": "https://mundotek.com.ec/producto/oppo-a5-4g-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m18",
    "source": "mundotek",
    "name": "Motorola moto g15 4G",
    "specs": "Almacenamiento: 256GB , 512GB · 512GB-256GB · 512GB · 256GB · 48gb",
    "price": 169.0,
    "image": "imagenes/28-motorola-moto-g15-4g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/g15.png",
    "url": "https://mundotek.com.ec/producto/motorola-moto-g15-ram-48gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m19",
    "source": "mundotek",
    "name": "Tecno Spark 9 Pro",
    "specs": "Tecno Spark 9 Pro",
    "price": 175.0,
    "image": "imagenes/29-tecno-spark-9-pro.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/11/Tecno-Spark-9-Pro-4.jpg",
    "url": "https://mundotek.com.ec/producto/tecno-spark-9-pro/",
    "badge": "Precio bajo"
  },
  {
    "id": "m20",
    "source": "mundotek",
    "name": "Xiaomi Redmi 15c",
    "specs": "256gb · 8gb",
    "price": 179.0,
    "image": "imagenes/30-xiaomi-redmi-15c.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/redmi15c.webp",
    "url": "https://mundotek.com.ec/producto/xiaomi-redmi-15c-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m21",
    "source": "mundotek",
    "name": "Honor X6c",
    "specs": "Memoria Ram: 6GB , 8GB · 256GB · 6GB · 8GB",
    "price": 185.0,
    "image": "imagenes/31-honor-x6c.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/06/x6c.webp",
    "url": "https://mundotek.com.ec/producto/honor-x6c-ram-6gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m22",
    "source": "mundotek",
    "name": "Motorola G17",
    "specs": "4GB · 256GB",
    "price": 185.0,
    "image": "imagenes/32-motorola-g17.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/moto-g17.jpg",
    "url": "https://mundotek.com.ec/producto/motorola-g17-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m23",
    "source": "mundotek",
    "name": "Realme Narzo 30 (5G)",
    "specs": "5G · Peso: 0.18 kg",
    "price": 195.0,
    "image": "imagenes/33-realme-narzo-30-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/11/719tm7l723L._SL1500_.jpg",
    "url": "https://mundotek.com.ec/producto/realme-narzo-30-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "m24",
    "source": "mundotek",
    "name": "Celular Oukitel G1 24 (6+18) Gb",
    "specs": "256 Gb",
    "price": 225.0,
    "image": "imagenes/34-celular-oukitel-g1-24-6-18-gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/g1.jpg",
    "url": "https://mundotek.com.ec/producto/celular-oukitel-g1-24-618-gb-ram-256-gb-color-negro/",
    "badge": "Precio bajo"
  },
  {
    "id": "m25",
    "source": "mundotek",
    "name": "Honor X7d",
    "specs": "Memoria Ram: 6GB , 8GB · 256GB · 6GB · 88gb",
    "price": 229.0,
    "image": "imagenes/35-honor-x7d.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/10/honor-x7d.jpg",
    "url": "https://mundotek.com.ec/producto/honor-x7d-ram-88gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m26",
    "source": "mundotek",
    "name": "Celular Zte Nubia Air 5G –",
    "specs": "5G · 256GB",
    "price": 235.0,
    "image": "imagenes/36-celular-zte-nubia-air-5g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/celular-zte-nubia-air-5g.png",
    "url": "https://mundotek.com.ec/producto/celular-zte-nubia-air-5g-ram-812-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m27",
    "source": "mundotek",
    "name": "Honor 90 lite",
    "specs": "8GB · 256GB",
    "price": 239.0,
    "image": "imagenes/37-honor-90-lite.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/honor-90-lite-.jpg",
    "url": "https://mundotek.com.ec/producto/honor-90-lite-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m28",
    "source": "mundotek",
    "name": "Infinix Hot 60 pro plus 8+8GB",
    "specs": "Infinix Hot 60 pro plus 8+8GB 256GB · 8GB · 256GB · 88gb",
    "price": 255.0,
    "image": "imagenes/38-infinix-hot-60-pro-plus-8-8gb.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/07/hot60pro.png",
    "url": "https://mundotek.com.ec/producto/infinix-hot-60-pro-plus-88gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m29",
    "source": "mundotek",
    "name": "SAMSUNG GALAXY A17",
    "specs": "Almacenamiento: 128GB , 256GB · SAMSUNG GALAXY A17 8GB -256GB Androir · 8GB · 256GB · 4gb · 128gb",
    "price": 259.0,
    "image": "imagenes/39-samsung-galaxy-a17.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/sam-a17-4g.webp",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a17-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m30",
    "source": "mundotek",
    "name": "Xiaomi Mi 10 lite",
    "specs": "6gb Ram · 5G · Peso: 0.19 kg · 128gb · 6gb",
    "price": 269.0,
    "image": "imagenes/40-xiaomi-mi-10-lite.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/08/logo-sin-fondo-1024x1024.png",
    "url": "https://mundotek.com.ec/producto/xiaomi-mi-10-lite-128gb-6gb-ram-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "m31",
    "source": "mundotek",
    "name": "OPPO A5 5G",
    "specs": "5G · 256GB · 8GB",
    "price": 269.0,
    "image": "imagenes/41-oppo-a5-5g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/oppoa5.png",
    "url": "https://mundotek.com.ec/producto/oppo-a5-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m32",
    "source": "mundotek",
    "name": "Redmi Note 15 Pro 4G",
    "specs": "8Gb · 256Gb",
    "price": 299.0,
    "image": "imagenes/42-redmi-note-15-pro-4g.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/xiaomi-redmi-note-15-pro-4g.webp",
    "url": "https://mundotek.com.ec/producto/redmi-note-15-4g-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m33",
    "source": "mundotek",
    "name": "Tecno camon 18 premier",
    "specs": "Peso: 0.2 kg",
    "price": 315.0,
    "image": "imagenes/43-tecno-camon-18-premier.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/04/camon-.jpg",
    "url": "https://mundotek.com.ec/producto/tecno-camon-18-premier/",
    "badge": "Precio bajo"
  },
  {
    "id": "m34",
    "source": "mundotek",
    "name": "Oppo A5 PRO (5G) Ram8GB/256GB IP69 SUMERGIBLE",
    "specs": "5G · 8GB · 256GB",
    "price": 319.0,
    "image": "imagenes/44-oppo-a5-pro-5g-ram8gb-256gb-ip69-sumergible.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/oppo-a5pro.webp",
    "url": "https://mundotek.com.ec/producto/oppo-a5-pro-5g-ram8gb-256gb-ip69-sumergible/",
    "badge": "Precio bajo"
  },
  {
    "id": "m35",
    "source": "mundotek",
    "name": "HONOR X8d",
    "specs": "Almacenamiento: 256GB , 512GB · 8GB · 256GB · 512GB",
    "price": 319.0,
    "image": "imagenes/45-honor-x8d.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/honor-x8d.webp",
    "url": "https://mundotek.com.ec/producto/honor-x8d-ram-8gb-256gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m36",
    "source": "mundotek",
    "name": "Tecno Camón 50 pro",
    "specs": "8 GB · 256GB",
    "price": 339.0,
    "image": "imagenes/46-tecno-cam-n-50-pro.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/camon-con-audifonos.png",
    "url": "https://mundotek.com.ec/producto/tecno-camon-50-pro-ram-88-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m37",
    "source": "mundotek",
    "name": "Samsung Galaxy A36 5G",
    "specs": "5G · 256GB · 8GB",
    "price": 349.0,
    "image": "imagenes/47-samsung-galaxy-a36-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/a36-black-mtk.jpg",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a36-5g-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m38",
    "source": "mundotek",
    "name": "XIAOMI POCO F4",
    "specs": "Memoria Ram: 6GB , 8GB · Peso: 0.19 kg · 256GB · 8GB",
    "price": 399.0,
    "image": "imagenes/48-xiaomi-poco-f4.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/08/Nuevo-proyecto-11-1.png",
    "url": "https://mundotek.com.ec/producto/xiaomi-poco-f4-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m39",
    "source": "mundotek",
    "name": "Honor Magic8 Lite",
    "specs": "Almacenamiento: 256GB , 512GB · 8GB · 256GB · 512GB",
    "price": 409.0,
    "image": "imagenes/49-honor-magic8-lite.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/01/magi-8lite.webp",
    "url": "https://mundotek.com.ec/producto/honor-magic8-lite-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m40",
    "source": "mundotek",
    "name": "Infinix Note 60 Pro 5G",
    "specs": "5G · 8 GB · 256GB",
    "price": 419.0,
    "image": "imagenes/50-infinix-note-60-pro-5g.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/note60pro.webp",
    "url": "https://mundotek.com.ec/producto/infinix-note-60-pro-5g-ram-88-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m41",
    "source": "mundotek",
    "name": "Motorola Edge 70 Fusion",
    "specs": "8GB · 256GB",
    "price": 419.0,
    "image": "imagenes/51-motorola-edge-70-fusion.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/70-fushion.png",
    "url": "https://mundotek.com.ec/producto/motorola-edge-70-fusion-ram-8gb-256gb-buds-motorola/",
    "badge": "Precio bajo"
  },
  {
    "id": "m42",
    "source": "mundotek",
    "name": "Samsung Galaxy A37 5G",
    "specs": "5G · 8GB · 256GB",
    "price": 419.0,
    "image": "imagenes/52-samsung-galaxy-a37-5g.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/a37.webp",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a37-5g-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m43",
    "source": "mundotek",
    "name": "Samsung Galaxy A56 5G",
    "specs": "Almacenamiento: 128GB , 256GB · 5G · 256GB · 12GB",
    "price": 439.0,
    "image": "imagenes/53-samsung-galaxy-a56-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/a56.jpg",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a56-5g-ram-12gb-256gb-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "m44",
    "source": "mundotek",
    "name": "Honor 600E",
    "specs": "8GB · 256GB",
    "price": 449.0,
    "image": "imagenes/54-honor-600e.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/honor-e.webp",
    "url": "https://mundotek.com.ec/producto/honor-600e-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m45",
    "source": "mundotek",
    "name": "Redmi Note 15 Pro Plus 5G",
    "specs": "5G · 12GB · 512GB",
    "price": 489.0,
    "image": "imagenes/55-redmi-note-15-pro-plus-5g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/xiaomi-redmi-note15-pro-plus.png",
    "url": "https://mundotek.com.ec/producto/redmi-note-15-pro-plus-5g-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m46",
    "source": "mundotek",
    "name": "Oppo Reno13F 5G",
    "specs": "5G · 512GB IP69 · 12GB · 512GB",
    "price": 499.0,
    "image": "imagenes/56-oppo-reno13f-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/reno-13f.jpg",
    "url": "https://mundotek.com.ec/producto/reno13-f-5g-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m47",
    "source": "mundotek",
    "name": "Oppo Reno14F",
    "specs": "12GB · 512GB",
    "price": 535.0,
    "image": "imagenes/57-oppo-reno14f.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/01/reno.webp",
    "url": "https://mundotek.com.ec/producto/oppo-reno14f-ram-12gb-512gb-audifonos/",
    "badge": "Precio bajo"
  },
  {
    "id": "m48",
    "source": "mundotek",
    "name": "Samsung Galaxy A57",
    "specs": "Memoria Ram: 12GB , 8GB · 8GB · 12GB · 256GB",
    "price": 549.0,
    "image": "imagenes/58-samsung-galaxy-a57.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/a57.png",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a57-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m49",
    "source": "mundotek",
    "name": "Xiaomi Poco x8 Pro",
    "specs": "512GB · 12GB",
    "price": 569.0,
    "image": "imagenes/59-xiaomi-poco-x8-pro.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/x8-pro.jpg",
    "url": "https://mundotek.com.ec/producto/xiaomi-poco-x8-pro-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m50",
    "source": "mundotek",
    "name": "IPHONE 11 PRO MAX OPEN BOX A",
    "specs": "Peso: 0.22 kg · IPHONE 11 PRO MAX OPEN BOX A 256GB · 256GB",
    "price": 579.0,
    "image": "imagenes/60-iphone-11-pro-max-open-box-a.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/09/11-pro-max-p.jpg",
    "url": "https://mundotek.com.ec/producto/iphone-11-pro-max-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "m51",
    "source": "mundotek",
    "name": "Samsung Galaxy S25 FE",
    "specs": "256GB 5G · 5G · 8GB · 256GB",
    "price": 579.0,
    "image": "imagenes/61-samsung-galaxy-s25-fe.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/12/samsung_galaxy_s25_fe.png",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-s25-fe-ram-8gb-256gb-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "m52",
    "source": "mundotek",
    "name": "Infinix GT 50 Pro HydroFlow y gatillos laterales",
    "specs": "12 GB · 256GB",
    "price": 599.0,
    "image": "imagenes/62-infinix-gt-50-pro-hydroflow-y-gatillos-laterales.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/07/infinix-gt-50-pro-launched-in-ph-c.jpg",
    "url": "https://mundotek.com.ec/producto/infinix-gt-50-pro-hydroflow-y-gatillos-laterales-ram-1212-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "t1",
    "source": "mundotek-tv",
    "name": "Box Xiaomi Mi Box S 3era Generacion 4K",
    "specs": "TV Box Xiaomi Mi Box S 3era Generacion 4K · Peso: 0.14 kg",
    "price": 89.0,
    "image": "imagenes/63-box-xiaomi-mi-box-s-3era-generacion-4k.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/06/tvbox2.webp",
    "url": "https://mundotek.com.ec/producto/tv-box-xiaomi-mi-box-s/",
    "badge": "#1 más económico"
  },
  {
    "id": "t2",
    "source": "mundotek-tv",
    "name": "House Tv HT-32 32 » hd led",
    "specs": "Pulgadas: 32″ · android · Smart tv",
    "price": 135.0,
    "image": "imagenes/64-house-tv-ht-32-32-hd-led.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/07/hausetv.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-house-tv-ht-32-32-fhd-led-android-14-definicion-full-hd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t3",
    "source": "mundotek-tv",
    "name": "Philips ph 32gfs fisdb 32",
    "specs": "Pulgadas: 32″ · android · google tv · Smart tv",
    "price": 155.0,
    "image": "imagenes/65-philips-ph-32gfs-fisdb-32.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/tv-philips32.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-philips-ph-32gfs-fisdb-32-hd-led-android-14-google-tv-mando-de-voz-sin-bordes/",
    "badge": "Precio bajo"
  },
  {
    "id": "t4",
    "source": "mundotek-tv",
    "name": "RCA 32 HDRC",
    "specs": "Pulgadas: 32″ · Televisor RCA 32 HDRC",
    "price": 155.0,
    "image": "imagenes/66-rca-32-hdrc.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/tvrca.webp",
    "url": "https://mundotek.com.ec/producto/televisor-rca-32-hdrc/",
    "badge": "Precio bajo"
  },
  {
    "id": "t5",
    "source": "mundotek-tv",
    "name": "Riviera RI-RLED – GLT32TPXM 32 » hd (1366×768) led hdr",
    "specs": "android · google tv · Smart tv",
    "price": 159.0,
    "image": "imagenes/67-riviera-ri-rled-glt32tpxm-32-hd-1366-768-led-hdr.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/ri-rled-glt32tpxm.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-ri-rled-glt32tpxm-32-hd-1366x768-led-hdr-android-google-tv-mando-de-voz/",
    "badge": "Precio bajo"
  },
  {
    "id": "t6",
    "source": "mundotek-tv",
    "name": "Innova IN-LED-32HD-GTV-MP 32 » hd led",
    "specs": "Pulgadas: 32″ · android · google tv · Smart tv",
    "price": 159.0,
    "image": "imagenes/68-innova-in-led-32hd-gtv-mp-32-hd-led.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/in-led32hd-gtv-mp.jpg",
    "url": "https://mundotek.com.ec/producto/13477/",
    "badge": "Precio bajo"
  },
  {
    "id": "t7",
    "source": "mundotek-tv",
    "name": "Hisense 32Q4Q Qled sistema operativo Vida",
    "specs": "Pulgadas: 32″ · Tv Hisense 32Q4Q Qled sistema operativo Vida",
    "price": 169.0,
    "image": "imagenes/69-hisense-32q4q-qled-sistema-operativo-vida.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/hisense-serie-a4-smart-tv-a4q.png",
    "url": "https://mundotek.com.ec/producto/tv-hisense-32q4q-qled-sistema-operativo-vida/",
    "badge": "Precio bajo"
  },
  {
    "id": "t8",
    "source": "mundotek-tv",
    "name": "Motorola 32Tmkfhd",
    "specs": "Pulgadas: 32″ · Tv Motorola 32Tmkfhd GOOGLE TV 32PULGADAS · GOOGLE TV · android · 32PULGADAS",
    "price": 170.0,
    "image": "imagenes/70-motorola-32tmkfhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/03/32tmkgfhd.jpg",
    "url": "https://mundotek.com.ec/producto/tv-motorola-32tmkgfhd-android-11-32pulgadas/",
    "badge": "Precio bajo"
  },
  {
    "id": "t9",
    "source": "mundotek-tv",
    "name": "Google QLED Riviera",
    "specs": "Pulgadas: 32″ · Televisor Google QLED Riviera 32″ GLT32TPQ10 · 32″",
    "price": 175.0,
    "image": "imagenes/71-google-qled-riviera.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/ri-rled-glt32tpq10.jpeg",
    "url": "https://mundotek.com.ec/producto/televisor-google-qled-riviera-32-glt32tpq10/",
    "badge": "Precio bajo"
  },
  {
    "id": "t10",
    "source": "mundotek-tv",
    "name": "Tcl 32S5K 32 » fhd qled",
    "specs": "Pulgadas: 32″ · android · google tv · Smart tv",
    "price": 185.0,
    "image": "imagenes/72-tcl-32s5k-32-fhd-qled.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/s5k32.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-tcl-32s5k-32-fhd-qled-android-14-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t11",
    "source": "mundotek-tv",
    "name": "Google LED HD Indurama",
    "specs": "Pulgadas: 32″ · Televisor Google LED HD Indurama 32″ 32TIKGF5HD · 32″",
    "price": 185.0,
    "image": "imagenes/73-google-led-hd-indurama.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/32tikgf5hd.jpeg",
    "url": "https://mundotek.com.ec/producto/televisor-google-led-hd-indurama-32-32tikgf5hd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t12",
    "source": "mundotek-tv",
    "name": "HouseTV Televisor HouseTV",
    "specs": "HouseTV Televisor HouseTV 40″ Android 14 · Pulgadas: 40″ · 40″ · Android",
    "price": 185.0,
    "image": "imagenes/74-housetv-televisor-housetv.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/tv40.png",
    "url": "https://mundotek.com.ec/producto/housetv-televisor-housetv-40-android-14/",
    "badge": "Precio bajo"
  },
  {
    "id": "t13",
    "source": "mundotek-tv",
    "name": "Lg 32lr650bpsa",
    "specs": "Pulgadas: 32″ · LG SMART TV 32» SMART TV con ThinQ AI 32LR650BPSA · SMART TV",
    "price": 199.0,
    "image": "https://mundotek.com.ec/wp-content/uploads/2025/01/32lr650bpsa.avif",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/32lr650bpsa.avif",
    "url": "https://mundotek.com.ec/producto/pantalla-lg-smart-tv-32-smart-tv-con-thinq-ai-32lr650bpsa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t14",
    "source": "mundotek-tv",
    "name": "House Tv HT-43 43 » fhd led",
    "specs": "Pulgadas: 43″ · android · Smart tv",
    "price": 209.0,
    "image": "imagenes/76-house-tv-ht-43-43-fhd-led.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/07/hausetv.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-house-tv-ht-43-43-fhd-led-android-14-definicion-full-hd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t15",
    "source": "mundotek-tv",
    "name": "Rca 40fhdrc 40",
    "specs": "Tv Rca 40FHDRC 40 » fhd led google tv dolby audio bluetooth · Pulgadas: 40″ · google tv · android",
    "price": 215.0,
    "image": "imagenes/77-rca-40fhdrc-40.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/40fhdrc-full-hd.jpg",
    "url": "https://mundotek.com.ec/producto/tv-rca-40fhdrc-40-fhd-led-android-11-google-tv-dolby-audio-bluetooth/",
    "badge": "Precio bajo"
  },
  {
    "id": "t16",
    "source": "mundotek-tv",
    "name": "Innova in tvled 40gfhd mp",
    "specs": "mart tv Innova IN-TVLED-40GFHD-MP 40 » fhd led android 11 google · Pulgadas: 40″ · android",
    "price": 219.0,
    "image": "imagenes/78-innova-in-tvled-40gfhd-mp.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/07/40gfhd-mp-google-tv.jpg",
    "url": "https://mundotek.com.ec/producto/mart-tv-innova-in-tvled-40gfhd-mp-40-fhd-led-android-11-google/",
    "badge": "Precio bajo"
  },
  {
    "id": "t17",
    "source": "mundotek-tv",
    "name": "RCA 43 FHDRC",
    "specs": "Pulgadas: 43″ · Televisor RCA 43 FHDRC",
    "price": 239.0,
    "image": "imagenes/79-rca-43-fhdrc.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/43fhdrc.webp",
    "url": "https://mundotek.com.ec/producto/televisor-rca-43-fhdrc/",
    "badge": "Precio bajo"
  },
  {
    "id": "t18",
    "source": "mundotek-tv",
    "name": "Motorola 43mknfhd/",
    "specs": "Televisor LED 43″ GOOGLE TV MOTOROLA 43MKNFHD · Pulgadas: 43″ · 43″ · GOOGLE TV",
    "price": 240.0,
    "image": "imagenes/80-motorola-43mknfhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/43mknfhd.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-led-43-google-tv-motorola-43mknfhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t19",
    "source": "mundotek-tv",
    "name": "Philips ph 43gfs fisdb 43",
    "specs": "Pulgadas: 43″ · android · Smart tv",
    "price": 245.0,
    "image": "imagenes/81-philips-ph-43gfs-fisdb-43.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/philips-43-gfs-fisdb-1.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-philips-ph-43gfs-fisdb-43-fhd-led-android-14-mando-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "t20",
    "source": "mundotek-tv",
    "name": "43 Pulgadas TCL (43S5400)",
    "specs": "Pulgadas: 43″ · Tv 43 Pulgadas TCL (43S5400) · 43 Pulgadas",
    "price": 249.0,
    "image": "imagenes/82-43-pulgadas-tcl-43s5400.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/08/s5400-front-.jpg",
    "url": "https://mundotek.com.ec/producto/tv-32-pulgadas-tcl-43s5400/",
    "badge": "Precio bajo"
  },
  {
    "id": "t21",
    "source": "mundotek-tv",
    "name": "Innova in",
    "specs": "Pulgadas: 43″ · android · google tv · Smart tv",
    "price": 249.0,
    "image": "imagenes/83-innova-in.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/12/tvled-43gfhd.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-innova-in-led-43fhd-gtv-mp-43-fhd-led-android-14-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t22",
    "source": "mundotek-tv",
    "name": "Hyundai FHD",
    "specs": "TV Hyundai FHD 43 pulgadas HYLED4326G Google TV · Pulgadas: 43″ · 43 pulgadas · Google TV",
    "price": 275.0,
    "image": "imagenes/84-hyundai-fhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/06/hyled4326g.jpg",
    "url": "https://mundotek.com.ec/producto/tv-hyundai-fhd-43-pulgadas-hyled4326g-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t23",
    "source": "mundotek-tv",
    "name": "Tcl 43S5K 43 » Qled",
    "specs": "TV Tcl 43S5K 43 » Qled android 14 google tv · Pulgadas: 43″ · android · google tv",
    "price": 275.0,
    "image": "imagenes/85-tcl-43s5k-43-qled.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/43s5k.jpg",
    "url": "https://mundotek.com.ec/producto/tv-tcl-43s5k-43-fhd-qled-android-14-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t24",
    "source": "mundotek-tv",
    "name": "Riviera ri rled glt43tpxm 43",
    "specs": "Pulgadas: 43″ · android · Smart tv",
    "price": 289.0,
    "image": "imagenes/86-riviera-ri-rled-glt43tpxm-43.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/riviera-43.webp",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-ri-rled-glt43tpxm-43-fhd-1920x1080-led-hdr-android-google-tv-mando-de-voz/",
    "badge": "Precio bajo"
  },
  {
    "id": "t25",
    "source": "mundotek-tv",
    "name": "Tcl 43%e2%80%b3",
    "specs": "TV TCL 43″ 4K HDR GOOGLE TV (P635) · Pulgadas: 43″ · 43″ 4K · GOOGLE TV",
    "price": 299.0,
    "image": "imagenes/87-tcl-43-e2-80-b3.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/11/Captura-de-pantalla_20221130_173941.png",
    "url": "https://mundotek.com.ec/producto/tv-tcl-43%e2%80%b3-4k-hdr-google-tv-p635/",
    "badge": "Precio bajo"
  },
  {
    "id": "t26",
    "source": "mundotek-tv",
    "name": "INDURAMA TV 43TIKJ5UHD",
    "specs": "Pulgadas: 43″ · SMART TV · 43Pulgadas",
    "price": 309.0,
    "image": "imagenes/88-indurama-tv-43tikj5uhd.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/02/tikhudhd.webp",
    "url": "https://mundotek.com.ec/producto/smart-tv-indurama-tv-43tikjuhd-43pulgadas/",
    "badge": "Precio bajo"
  },
  {
    "id": "t27",
    "source": "mundotek-tv",
    "name": "Lg 43pulgadas",
    "specs": "Pulgadas: 43″ · Televisor LG 43pulgadas UHD AI 43UA75 4K Smart TV 2025 · 43pulgadas UHD · Smart TV · 43pulgadas",
    "price": 325.0,
    "image": "imagenes/89-lg-43pulgadas.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/10/43ua75.webp",
    "url": "https://mundotek.com.ec/producto/televisor-lg-43pulgadas-uhd-ai-43ua75-4k-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t28",
    "source": "mundotek-tv",
    "name": "Samsung 50u8000",
    "specs": "Pulgadas: 50″ · Televisor Samsung LED 50″ Pulgadas Crystal UHD 4K 50U8000 · 50″",
    "price": 339.0,
    "image": "imagenes/90-samsung-50u8000.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/televisor-samsung-led-50-pulgadas-mtk.webp",
    "url": "https://mundotek.com.ec/producto/televisor-samsung-led-50%e2%80%b3-pulgadas-crystal-uhd-4k-50u8000/",
    "badge": "Precio bajo"
  },
  {
    "id": "t29",
    "source": "mundotek-tv",
    "name": "Rca uhdrc",
    "specs": "Pulgadas: 50″ · Televisor RCA 50 Pulgadas UHDRC · 50 Pulgadas UHD",
    "price": 340.0,
    "image": "imagenes/91-rca-uhdrc.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/50uhdrc.webp",
    "url": "https://mundotek.com.ec/producto/televisor-rca-50-pulgadas-uhdrc/",
    "badge": "Precio bajo"
  },
  {
    "id": "t30",
    "source": "mundotek-tv",
    "name": "Innova IN LED 50UHD GTV",
    "specs": "Sistema Operativo: : Google TV – Ultra High Definition 4K · TV Innova IN LED 50UHD GTV 50″ GOOGLE TV · Pulgadas: : Smart TV de 50» · Resolución: : 3840 x 2160 Ultra High Definition 4K · Pulgadas: 50″ · Contraste: : 5000: 1",
    "price": 345.0,
    "image": "imagenes/92-innova-in-led-50uhd-gtv.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/50uhd.png",
    "url": "https://mundotek.com.ec/producto/tv-innova-in-led-50uhd-gtv-50-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t31",
    "source": "mundotek-tv",
    "name": "Tcl 50S5K 50 » fhd qled",
    "specs": "Pulgadas: 50″ · android · google tv · Smart tv",
    "price": 349.0,
    "image": "imagenes/93-tcl-50s5k-50-fhd-qled.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/s5k.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-tcl-50s5k-50-fhd-qled-android-14-google-tv-panel-hva-qled/",
    "badge": "Precio bajo"
  },
  {
    "id": "t32",
    "source": "mundotek-tv",
    "name": "RIVIERA QLED 4K -GLT50TPQ10",
    "specs": "TV RIVIERA QLED 4K -GLT50TPQ10 50″ GOOGLE TV · Pulgadas: 50″ · 50″ · GOOGLE TV",
    "price": 369.0,
    "image": "imagenes/94-riviera-qled-4k--glt50tpq10.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/rled-glt50tpq10.png",
    "url": "https://mundotek.com.ec/producto/tv-riviera-qled-4k-glt50tpq10-50%e2%80%b3-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t33",
    "source": "mundotek-tv",
    "name": "Crystal UHD DU7000 4K de 50” con sistema operativo Tizen",
    "specs": "Televisor inteligente Crystal UHD DU7000 4K de 50” con sistema operativo Tizen · Pulgadas: 50″ · inteligente Crystal UHD DU7000 4K de 50” con siste · inteligente-crystal-uhd-du7000-4k-de-50-con-sistem",
    "price": 369.0,
    "image": "imagenes/95-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/du7000-mtk.webp",
    "url": "https://mundotek.com.ec/producto/televisor-inteligente-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen-oferta-de-verano/",
    "badge": "Precio bajo"
  },
  {
    "id": "t34",
    "source": "mundotek-tv",
    "name": "Indurama LED 4K50 Pulgadas (50TIKGF2GUHD",
    "specs": "Tv Indurama LED 4K50 Pulgadas (50TIKGF2GUHD Google Tv) · Pulgadas: 50″ · 50 Pulgadas · Google Tv",
    "price": 379.0,
    "image": "imagenes/96-indurama-led-4k50-pulgadas-50tikgf2guhd.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/10/d_nq_np_783527-mec53271187298_012023-o.webp",
    "url": "https://mundotek.com.ec/producto/tv-indurama-qled-50-pulgadas-50tikgf2guhd-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t35",
    "source": "mundotek-tv",
    "name": "Innova in",
    "specs": "Pulgadas: 55″ · 4k uhd · Smart tv",
    "price": 379.0,
    "image": "imagenes/97-innova-in.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/12/in-led55mtk.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-innova-in-led-55uhd-gtv-mp-55-4k-uhd-led/",
    "badge": "Precio bajo"
  },
  {
    "id": "t36",
    "source": "mundotek-tv",
    "name": "Rca led55rca684gt 55",
    "specs": "Pulgadas: 55″ · 4k uhd · android · google tv · Smart tv",
    "price": 399.0,
    "image": "imagenes/98-rca-led55rca684gt-55.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/07/rca684gt.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-rca-led55rca684gt-55-4k-uhd-led-android-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t37",
    "source": "mundotek-tv",
    "name": "Riviera rled glt55tpx9 55",
    "specs": "Pulgadas: 55″ · 4k uhd · android · google tv · Smart tv",
    "price": 399.0,
    "image": "imagenes/99-riviera-rled-glt55tpx9-55.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/google-tv-glt55px9.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-rled-glt55tpx9-55-4k-uhd-led-android-google-tv-color-negro/",
    "badge": "Precio bajo"
  },
  {
    "id": "t38",
    "source": "mundotek-tv",
    "name": "LG UHD AI 50UA7500 4K",
    "specs": "Pulgadas: 50″ · Televisor LG UHD AI 50UA7500 4K Smart TV · Smart TV",
    "price": 409.0,
    "image": "imagenes/100-lg-uhd-ai-50ua7500-4k.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/50ua7500.jpeg",
    "url": "https://mundotek.com.ec/producto/televisor-lg-uhd-ai-50ua7500-4k-smart-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t39",
    "source": "mundotek-tv",
    "name": "LG UHD 50» UR7300 4K",
    "specs": "LG UHD 50» UR7300 4K Smart TV con ThinQ AI , 4K Procesador Inteligente · Pulgadas: 50″ · Smart TV · Inteligente https · inteligente",
    "price": 419.0,
    "image": "imagenes/101-lg-uhd-50-ur7300-4k.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/07/image-1.jpg",
    "url": "https://mundotek.com.ec/producto/lg-uhd-50-ur7300-4k-smart-tv-con-thinq-ai-4k-procesador-inteligente/",
    "badge": "Precio bajo"
  },
  {
    "id": "t40",
    "source": "mundotek-tv",
    "name": "Hisense 55%e2%80%b3",
    "specs": "Tv Hisense 55″ LED 4K Smart VIDAA 55A6H · Pulgadas: 55″ · 55″ · Peso: 16910 g · Dimensiones: 13 × 86 × 86 cm",
    "price": 419.0,
    "image": "imagenes/102-hisense-55-e2-80-b3.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/05/tv-hisense-55-55a6h.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-tv-hisense-55%e2%80%b3-led-4k-smart-vidaa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t41",
    "source": "mundotek-tv",
    "name": "Hisense 55Q6QV 55 » 4k uhd QLED Vidaa",
    "specs": "Televisor Hisense 55Q6QV 55 » 4k uhd QLED Vidaa · Pulgadas: 55″ · 4k uhd",
    "price": 419.0,
    "image": "imagenes/103-hisense-55q6qv-55-4k-uhd-qled-vidaa.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/55q6qv.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-hisense-55q6qv-55-4k-uhd-qled-vidaa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t42",
    "source": "mundotek-tv",
    "name": "55Pulgadas TCL P6K 4K UHD",
    "specs": "Pulgadas: 55″ · Televisor 55Pulgadas TCL P6K 4K UHD · 4K UHD · 55Pulgadas",
    "price": 429.0,
    "image": "imagenes/104-55pulgadas-tcl-p6k-4k-uhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/tv-tcl-55-55p6k.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-55pulgadas-tcl-p6k-4k-uhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t43",
    "source": "mundotek-tv",
    "name": "Riviera QLED",
    "specs": "Pulgadas: 55″ · Televisor Riviera QLED 55″ RLED-GLT55TPQ10 · 55″",
    "price": 429.0,
    "image": "imagenes/105-riviera-qled.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/rled-glt55tpq10.webp",
    "url": "https://mundotek.com.ec/producto/televisor-riviera-qled-55-rled-glt55tpq10/",
    "badge": "Precio bajo"
  },
  {
    "id": "t44",
    "source": "mundotek-tv",
    "name": "Motorola 55MGFUHD Google 4K Tv",
    "specs": "Pulgadas: 55″ · Televisor Motorola 55MGFUHD Google 4K Tv 55″ · 55″",
    "price": 439.0,
    "image": "imagenes/106-motorola-55mgfuhd-google-4k-tv.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/mtk-tmkuhd.png",
    "url": "https://mundotek.com.ec/producto/televisor-motorola-55tmkuhd-google-tv-55/",
    "badge": "Precio bajo"
  },
  {
    "id": "t45",
    "source": "mundotek-tv",
    "name": "PHILIPS QLED",
    "specs": "Televisor PHILIPS QLED 55″ Pulgadas UHD 4K – Google TV – Q55gfu · Pulgadas: 55″ · 55″ · Google TV · 5g",
    "price": 439.0,
    "image": "imagenes/107-philips-qled.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/55gfu.png",
    "url": "https://mundotek.com.ec/producto/televisor-philips-qled-55%e2%80%b3-pulgadas-uhd-4k-google-tv-q55gfu/",
    "badge": "Precio bajo"
  },
  {
    "id": "t46",
    "source": "mundotek-tv",
    "name": "Crystal UHD DU7000 4K de 50” con sistema operativo Tizen",
    "specs": "Televisor inteligente Crystal UHD DU7000 4K de 50” con sistema operativo Tizen · Pulgadas: 50″ · inteligente Crystal UHD DU7000 4K de 50” con siste · inteligente-crystal-uhd-du7000-4k-de-50-con-sistem",
    "price": 459.0,
    "image": "imagenes/108-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/du7000-mtk.webp",
    "url": "https://mundotek.com.ec/producto/televisor-inteligente-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen-2024-copia/",
    "badge": "Precio bajo"
  },
  {
    "id": "t47",
    "source": "mundotek-tv",
    "name": "Qled TCL 55T6C",
    "specs": "Pulgadas: 55″ · Televisor Qled TCL 55T6C 55 PULGADAS · 55 PULGADAS",
    "price": 469.0,
    "image": "imagenes/109-qled-tcl-55t6c.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/qled-tcl-t6c.webp",
    "url": "https://mundotek.com.ec/producto/televisor-qled-tcl-t6c-55-pulgadas/",
    "badge": "Precio bajo"
  },
  {
    "id": "t48",
    "source": "mundotek-tv",
    "name": "Samsung 50q7faa",
    "specs": "Pulgadas: 50″ · Samsung 50 pulgadas 50Q7FAA Series 4K Vision AI Smart TV · 50 pulgadas · Smart TV",
    "price": 489.0,
    "image": "https://mundotek.com.ec/wp-content/uploads/2026/04/q7faa-50.avif",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/q7faa-50.avif",
    "url": "https://mundotek.com.ec/producto/samsung-50-pulgadas-50q7faa-series-4k-vision-ai-smart-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t49",
    "source": "mundotek-tv",
    "name": "55″ Crystal UHD 4K 55U8000 Tizen OS",
    "specs": "TV 55″ Crystal UHD 4K 55U8000 Tizen OS Smart TV (2026) · Pulgadas: 55″ · 55″ · Smart TV",
    "price": 499.0,
    "image": "imagenes/111-55-crystal-uhd-4k-55u8000-tizen-os.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/ue65u8000.png",
    "url": "https://mundotek.com.ec/producto/tv-55-crystal-uhd-4k-u8000-tizen-os-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t50",
    "source": "mundotek-tv",
    "name": "INNOVA IN-TVLED-65GUHD-MP",
    "specs": "TELEVISOR INNOVA IN-TVLED-65GUHD-MP GOOGLE TV 65″ · Pulgadas: 65″ · 65″ · GOOGLE TV · 5G",
    "price": 519.0,
    "image": "https://mundotek.com.ec/wp-content/uploads/2026/04/tv65.avif",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/tv65.avif",
    "url": "https://mundotek.com.ec/producto/televisor-innova-in-tvled-65guhd-mp-google-tv-65/",
    "badge": "Precio bajo"
  },
  {
    "id": "t51",
    "source": "mundotek-tv",
    "name": "Philips Led 65GFS-FISDB",
    "specs": "Televisor Philips Led 65GFS-FISDB Google Tv 65″ · Pulgadas: 65″ · 65″ · Google Tv · 5G",
    "price": 525.0,
    "image": "imagenes/113-philips-led-65gfs-fisdb.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/philips-65-gfs-fisdb.png",
    "url": "https://mundotek.com.ec/producto/televisor-philips-led-65gfs-fisdb-google-tv-65/",
    "badge": "Precio bajo"
  },
  {
    "id": "t52",
    "source": "mundotek-tv",
    "name": "55″ LG UHD AI 4K",
    "specs": "Pulgadas: 55″ · 55″ LG UHD AI 4K Smart TV 55ua7300 2025 · 55″ · Smart TV",
    "price": 530.0,
    "image": "imagenes/114-55-lg-uhd-ai-4k.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/10/65ua73.webp",
    "url": "https://mundotek.com.ec/producto/55-lg-uhd-ai-4k-smart-tv-55ua7300-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t53",
    "source": "mundotek-tv",
    "name": "Samsung 55 mini",
    "specs": "Pulgadas: 75″ · Televisor Samsung 55″ Mini LED UHD UN55M70HAGXPE · 55″",
    "price": 539.0,
    "image": "imagenes/115-samsung-55-mini.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/nini-led-sam.webp",
    "url": "https://mundotek.com.ec/producto/televisor-samsung-55-mini-led-uhd-un55m70hagxpe/",
    "badge": "Precio bajo"
  },
  {
    "id": "t54",
    "source": "mundotek-tv",
    "name": "Lg 60",
    "specs": "Pulgadas: 60″ · Televisor LG 60″ LED 4K UHD 60UA8500PSA · 60″ · 4K UHD",
    "price": 549.0,
    "image": "imagenes/116-lg-60.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/60ua85.webp",
    "url": "https://mundotek.com.ec/producto/televisor-lg-60-led-4k-uhd-60ua8500psa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t55",
    "source": "mundotek-tv",
    "name": "Pantalla LG NanoCell 55» NANO80TSA 4K",
    "specs": "Pulgadas: 55″ · Pantalla LG NanoCell 55» NANO80TSA 4K SMART TV con ThinQ AI · SMART TV",
    "price": 555.0,
    "image": "imagenes/117-pantalla-lg-nanocell-55-nano80tsa-4k.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/09/55nano77.webp",
    "url": "https://mundotek.com.ec/producto/pantalla-lg-nanocell-55-nano77-4k-smart-tv-con-thinq-ai/",
    "badge": "Precio bajo"
  },
  {
    "id": "t56",
    "source": "mundotek-tv",
    "name": "Riviera glt65px9 65",
    "specs": "Pulgadas: 65″ · 4k uhd · android · google tv · Smart tv",
    "price": 569.0,
    "image": "imagenes/118-riviera-glt65px9-65.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/tv-glt65px9.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-glt65px9-65-4k-uhd-led-android-google-tv-sin-borde-mando-de-voz-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t57",
    "source": "mundotek-tv",
    "name": "Motorola 65",
    "specs": "Pulgadas: 65″ · Televisor Motorola 65″ LED 4K UHD 65MNUHD · 65″ · 4K UHD",
    "price": 569.0,
    "image": "imagenes/119-motorola-65.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/65mnuhd.webp",
    "url": "https://mundotek.com.ec/producto/televisor-motorola-65-led-4k-uhd-65mnuhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t58",
    "source": "mundotek-tv",
    "name": "65″ INDURAMA UHD",
    "specs": "Televisor 65″ INDURAMA UHD Google Tv TIKGF2GUHD · Pulgadas: 65″ · 65″ · Google Tv",
    "price": 580.0,
    "image": "imagenes/120-65-indurama-uhd.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/65-tikgf2gudh-4k-google-tv.png",
    "url": "https://mundotek.com.ec/producto/televisor-65-indurama-uhd-google-tv-tikgf2guhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t59",
    "source": "mundotek-tv",
    "name": "Samsung vision ai",
    "specs": "Pulgadas: 55″ · Tv Samsung 55″ QLED Q7FAA 4K Vision AI Smart TV (2025) · 55″ QLED · Smart TV",
    "price": 589.0,
    "image": "imagenes/121-samsung-vision-ai.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/tv.webp",
    "url": "https://mundotek.com.ec/producto/55-qled-q7f-4k-samsung-vision-ai-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t60",
    "source": "mundotek-tv",
    "name": "65Pulgadas TCL P6K 4K UHD",
    "specs": "Pulgadas: 65″ · Televisor 65Pulgadas TCL P6K 4K UHD · 4K UHD · 65Pulgadas",
    "price": 599.0,
    "image": "imagenes/122-65pulgadas-tcl-p6k-4k-uhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/p6k.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-65pulgadas-tcl-p6k-4k-uhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t61",
    "source": "mundotek-tv",
    "name": "Hisense Hi-QLED MiniLED",
    "specs": "TV Hisense Hi-QLED MiniLED 55″ 4K 55U6ESG Google TV 2026 · Pulgadas: 55″ · 55″ 4K · Google TV",
    "price": 599.0,
    "image": "imagenes/123-hisense-hi-qled-miniled.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/50u6esg.webp",
    "url": "https://mundotek.com.ec/producto/tv-hisense-hi-qled-miniled-55-4k-55u6esg-google-tv-2026/",
    "badge": "Precio bajo"
  }
];
