window.catalogProducts = [
  {
    "id": "p1",
    "source": "pinsoft",
    "name": "ENV Book Pro Max",
    "specs": "Intel® Celeron® N4020 · 256GB SSD · 14.1\" Full HD, IPS · Windows 11 (Preinstalado) · Wi-Fi 5 AC · Teclado Español alfanumérico",
    "price": 319.0,
    "image": "https://www.pinsoft.ec/getimage/products/1%28155%29.png",
    "image_remote": "https://www.pinsoft.ec/getimage/products/1%28155%29.png",
    "url": "https://www.pinsoft.ec/cod-1768-laptop-env-book-pro-max-intel-celeron-n4020-8gb-256gb-ssd-14-1-full-hd-ips-windows-11-preinstalado-wi-fi-5-ac-teclado-espanol-alfanumerico-gris-oscuro/p-9535.html",
    "badge": "#1 más económico"
  },
  {
    "id": "p2",
    "source": "pinsoft",
    "name": "ENV BOOK ELITE",
    "specs": "AMD Ryzen™ 5 3500U ( 2.1GHz hasta 3.7GHz) · 256GB NVMe™ SSD · 15.6\" Full HD · Windows 11 (Preinstalado) · Teclado Español alfanumérico · 8GB",
    "price": 374.0,
    "image": "https://www.pinsoft.ec/getimage/products/1%28156%29.png",
    "image_remote": "https://www.pinsoft.ec/getimage/products/1%28156%29.png",
    "url": "https://www.pinsoft.ec/cod-1780-laptop-env-book-elite-amd-ryzen-5-3500u-2-1ghzhasta-3-7ghz-8gb-256gb-nvme-ssd-15-6-full-hd-windows-11-teclado-espanol-alfanumerico-gris-oscuro/p-9623.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p3",
    "source": "pinsoft",
    "name": "HP 14-dq3500la",
    "specs": "Intel® Celeron® N4500 · 256GB PCIe® NVMe™ SSD · 14.0\" HD · FreeDOS · Wi-Fi 6 & BT 5.4 · Teclado Español",
    "price": 405.9,
    "image": "https://www.pinsoft.ec/getimage/products/thumbs_500_0bb2991cbc8280bc205e%281%29.png",
    "image_remote": "https://www.pinsoft.ec/getimage/products/thumbs_500_0bb2991cbc8280bc205e%281%29.png",
    "url": "https://www.pinsoft.ec/cod-h-1779-hp-14-dq3500la-intel-celeron-n4500-8gb-256gb-pcie-nvme-ssd-14-0-hd-wi-fi-6-bt-5-4-freedos-teclado-espanol-plateado-natural/p-9621.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p4",
    "source": "pinsoft",
    "name": "LENOVO IdeaPad Slim 3 15AMN8",
    "specs": "AMD Ryzen™ 3 7320U · 512GB NVMe SSD M.2 · 15.6\" FHD · Wi-Fi®6 2x2 & BT5.2 · Teclado Español alfanumérico · 8GB LPDDR5",
    "price": 462.0,
    "image": "https://www.pinsoft.ec/getimage/products/laptop-ideapad-slim-3-amd-r3-732.png",
    "image_remote": "https://www.pinsoft.ec/getimage/products/laptop-ideapad-slim-3-amd-r3-732.png",
    "url": "https://www.pinsoft.ec/cod-1791-lenovo-ideapad-slim-3-15amn8-amd-ryzen-3-7320u-8gb-lpddr5-512gb-nvme-ssd-m-2-15-6-fhd-sin-sistema-os-wi-fi6-2x2-bt5-2-teclado-espanol-alfanumerico-artic-grey/p-9675.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p5",
    "source": "pinsoft",
    "name": "ASUS VivoBook Go 15 (E1504F)",
    "specs": "AMD® Ryzen™ 3 7320U · 512GB NVMe™ SSD · 15.6\" FHD · Wi-Fi 6E& BT 5.3 · Teclado Español alfanumérico · 8 GB LPDDR5",
    "price": 473.0,
    "image": "https://www.pinsoft.ec/getimage/products/17951111.jpg",
    "image_remote": "https://www.pinsoft.ec/getimage/products/17951111.jpg",
    "url": "https://www.pinsoft.ec/cod-1795-asus-vivobook-go-15-e1504f-amd-ryzen-37320u-8-gb-lpddr5-512gb-nvme-ssd-15-6-fhd-sin-sistema-os-wi-fi-6e-bt-5-3-lector-de-huellas-teclado-espanol-alfanumerico-mixed-black-incl-mouseasus/p-9701.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p6",
    "source": "pinsoft",
    "name": "ENV 3500u",
    "specs": "AMD Ryzen™ 5 3500U ( 2.1GHz hasta 3.7GHz) · 512GB NVMe™ SSD · 15.6\" Full HD · Windows 11 (Preinstalado) · Teclado Español alfanumérico · 16GB",
    "price": 484.0,
    "image": "https://www.pinsoft.ec/getimage/products/pinsoft-env12%288%29.jpg",
    "image_remote": "https://www.pinsoft.ec/getimage/products/pinsoft-env12%288%29.jpg",
    "url": "https://www.pinsoft.ec/cod-e-1776-laptop-env-amd-ryzen-5-3500u-2-1ghzhasta-3-7ghz-16gb-512gb-nvme-ssd-15-6-full-hd-windows-11-teclado-espanol-alfanumerico-gris/p-9592.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p7",
    "source": "pinsoft",
    "name": "ENV 3500u",
    "specs": "AMD Ryzen™ 5 3500U ( 2.1GHz hasta 3.7GHz) · 512GB NVMe™ SSD · 14.1\" Full HD · Windows 11 (Preinstalado) · Teclado Español · 16GB",
    "price": 484.0,
    "image": "https://www.pinsoft.ec/getimage/products/11%2875%29.jpg",
    "image_remote": "https://www.pinsoft.ec/getimage/products/11%2875%29.jpg",
    "url": "https://www.pinsoft.ec/cod-1775-laptop-env-amd-ryzen-5-3500u-2-1ghzhasta-3-7ghz-16gb-512gb-nvme-ssd-14-1-full-hd-windows-11-teclado-espanol-gris/p-9593.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p8",
    "source": "pinsoft",
    "name": "LENOVO IdeaPad Slim 3 15IAN8",
    "specs": "Intel® Core™ i3-N305 (8 núcleos, hasta 3.8 GHz) · 512GB SSD PCIe® 4.0 · 15.6\" Full HD · Wi-Fi 6 & BT5.2 · Teclado Español (LA) alfanumérico · 8GB LPDDR5",
    "price": 511.5,
    "image": "https://www.pinsoft.ec/getimage/products/windows10home-64bits%283%29.png",
    "image_remote": "https://www.pinsoft.ec/getimage/products/windows10home-64bits%283%29.png",
    "url": "https://www.pinsoft.ec/cod-1787-lenovo-ideapad-slim-3-15ian8-intel-core-i3-n305-8-nucleos-hasta-3-8-ghz-8gb-lpddr5-512gb-ssd-pcie-4-0-15-6-full-hd-sin-sistema-os-wi-fi-6-bt5-2-teclado-espanol-la-alfanumerico-arctic-grey/p-9649.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p9",
    "source": "pinsoft",
    "name": "ASUS VivoBook 15 X1504V",
    "specs": "Intel® Core™ i3-1315U 13va. Gen (10MB caché, hasta 4,4 GHz) · 512GB NVMe™ SSD · 15.6\" FHD · Wi-Fi 6E& BT 5.3 · Teclado Español alfanumérico · 8GB",
    "price": 517.0,
    "image": "https://www.pinsoft.ec/getimage/products/pinsoft-1698%283%29.jpg",
    "image_remote": "https://www.pinsoft.ec/getimage/products/pinsoft-1698%283%29.jpg",
    "url": "https://www.pinsoft.ec/cod-1766-kit-asus-vivobook-15-x1504v-intel-corei3-1315u-13va-gen-10mb-cache-hasta-4-4-ghz-8gb-512gb-nvme-ssd-15-6-fhd/p-9534.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p10",
    "source": "pinsoft",
    "name": "ASUS VivoBook 15 X1504V",
    "specs": "Intel® Core™ i3-1315U 13va. Gen (10MB caché, hasta 4,4 GHz) · 512GB NVMe™ SSD · 15.6\" FHD · Wi-Fi 6E& BT 5.3 · Teclado Español alfanumérico · 16GB",
    "price": 566.5,
    "image": "https://www.pinsoft.ec/getimage/products/pinsoft-1698%284%29.jpg",
    "image_remote": "https://www.pinsoft.ec/getimage/products/pinsoft-1698%284%29.jpg",
    "url": "https://www.pinsoft.ec/cod-1774-kit-asus-vivobook-15-x1504v-intel-corei3-1315u-13va-gen-10mb-cache-hasta-4-4-ghz-16gb-512gb-nvme/p-9588.html",
    "badge": "Precio bajo"
  },
  {
    "id": "p11",
    "source": "pinsoft",
    "name": "LENOVO V15 G5 IRL",
    "specs": "Intel® Core™ i5-13420H 13va.Gen · 512GB SSD PCIe 4.0 · 15.6\" Full HD · Wi-Fi 6 AX · Teclado alfanumérico Español (LA) · 8GB DDR5",
    "price": 605.0,
    "image": "https://www.pinsoft.ec/getimage/products/lenovo_v15_g5_irl_ct1_06%281%29.png",
    "image_remote": "https://www.pinsoft.ec/getimage/products/lenovo_v15_g5_irl_ct1_06%281%29.png",
    "url": "https://www.pinsoft.ec/cod-1793-lenovo-v15-g5-irl-intel-core-i5-13420h-13va-gen-8gb-ddr5-512gb-ssd-pcie-4-0-15-6-full-hd-sin-sistema-os-wi-fi-6-ax-teclado-alfanumerico-espanol-la-luna-grey/p-9681.html",
    "badge": "Precio bajo"
  },
  {
    "id": "pd1",
    "source": "planeta-digital",
    "name": "HP 14 I3 N305",
    "specs": "Tarjeta de video: Intel® UHD Graphics integrada · Procesador: Intel® Core™ i3-N305 (eficiente y adecuado para tareas básicas y uso diario) · Memoria RAM: 4 GB DDR4 (suficiente para tareas básicas como navegación y ofimática) · Almacenamiento: 128 GB SSD PCIe® NVMe (arranque rápido, ideal para uso ligero) · Pantalla · Sistema operativo: Windows 11 Home",
    "price": 260.0,
    "image": "imagenes/12-hp-14-i3-n305.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/d_nq_np_2x_896627-mlu75842775050_042024-f-52c6dd934d8e53dcad17260675985400-480-0.webp?v=1727213717",
    "url": "https://planetadigitalec.com/products/hp-14-i3-n305-12gb-ram-512gb-ssd-14-copia",
    "badge": "#1 más económico"
  },
  {
    "id": "pd2",
    "source": "planeta-digital",
    "name": "GATEWAY",
    "specs": "Intel® UHD Graphics integrada (ideal para multimedia, streaming y uso básico) · Procesador · Memoria RAM · Disco · 128 GB SSD M.2 (arranque rápido y buena velocidad para tareas diarias) · Pantalla",
    "price": 279.0,
    "image": "imagenes/13-gateway.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/s-l1600_989c1eff-8a42-401c-ba2e-aadac0a841f7.webp?v=1777582649",
    "url": "https://planetadigitalec.com/products/gateway-intel-n100-128-gb-ssd-4-gb-ram-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd3",
    "source": "planeta-digital",
    "name": "HP 14 N150",
    "specs": "Procesador · Intel Processor N150 · Intel Graphics integrados · Memoria RAM · Almacenamiento · 128 GB SSD",
    "price": 290.0,
    "image": "imagenes/14-hp-14-n150.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/D_NQ_NP_705083-MLA87064978485_072025-O.webp?v=1790020963",
    "url": "https://planetadigitalec.com/products/hp-14-n150-4gb-ram-128gb-ssd-14",
    "badge": "Precio bajo"
  },
  {
    "id": "pd4",
    "source": "planeta-digital",
    "name": "Hp 15",
    "specs": "Intel UHD Graphics integrados · Procesador · Intel Processor N200 · Memoria RAM · Almacenamiento · 128 GB SSD",
    "price": 299.0,
    "image": "imagenes/15-hp-15.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/f0050123-0f6d-426d-adbf-795802bc5f74.ce05477936a0350f585f3b1bedcf1bba.avif?v=1790019631",
    "url": "https://planetadigitalec.com/products/hp-15-intel-200-4gb-ram-128gb-ssd-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd5",
    "source": "planeta-digital",
    "name": "ASUS VIVIBOOK GO",
    "specs": "Gráficos Intel UHD integrados, perfectos para uso casual · Procesador · Intel Core i3 N305 hasta 3,80 GHz: energía eficiente para las tareas diarias · Tamaño de RAM · Capacidad SSD · Tamaño de la pantalla",
    "price": 360.0,
    "image": "imagenes/16-asus-vivibook-go.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/s-l1600_7acd3a5a-51f2-4140-b795-4c7f32d52d68.webp?v=1762471471",
    "url": "https://planetadigitalec.com/products/asus-vivibook-go-intel-core-i3-12va-8gb-ram-512gb-ssd-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd6",
    "source": "planeta-digital",
    "name": "DELL INSPIRON 3530 I3-13VA",
    "specs": "Coprocesador de gráficos Intel UHD Graphics · Procesador ‎1.2 GHz core_i3_13va · Marca Chipset ‎Intel · Marca del procesador Intel · RAM 8GB DDR4 · Disco Duro 512 GB SSD",
    "price": 380.0,
    "image": "imagenes/17-dell-inspiron-3530-i3-13va.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/71iIEPk5qOL._AC_SX466.jpg?v=1772555363",
    "url": "https://planetadigitalec.com/products/dell-inspiron-3530-i3-13va-8gb-ram-512gb-ssd-15-7",
    "badge": "Precio bajo"
  },
  {
    "id": "pd7",
    "source": "planeta-digital",
    "name": "DELL LATITUDE 3540 I3-12VA",
    "specs": "Coprocesador de gráficos ‎Gráficos integrados Intel · Marca Chipset ‎Intel · Marca del procesador Intel · RAM 8GB DDR4 · Disco 256 GBSSD · Tamaño del área de visualización de la pantalla con pie ‎15,6 Pulgadas",
    "price": 380.0,
    "image": "imagenes/18-dell-latitude-3540-i3-12va.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/71e_cWKIj9L._AC_SX679_e2f13c4e-3a81-4fdf-8024-dca743d5656e.jpg?v=1721934705",
    "url": "https://planetadigitalec.com/products/dell-latitude-3540-i3-13va-8gb-ram-256gb-ssd-win-11-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd8",
    "source": "planeta-digital",
    "name": "ACER ASPIRE I3 N305",
    "specs": "Coprocesador de gráficos Intel UHD Graphics · Interfaz de la unidad de disco duro USB 3.0 · Procesador ‎3,8 GHz core_i3 N305 · Marca Chipset ‎Intel · Marca del procesador Intel · RAM ‎8 GB Lpddr 5",
    "price": 399.0,
    "image": "imagenes/19-acer-aspire-i3-n305.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/71VoWFZXjWL._AC_SX466.jpg?v=1760479917",
    "url": "https://planetadigitalec.com/products/acer-aspire-i3-n305-8gb-ram-256gb-ssd-touch-windows-11-14",
    "badge": "Precio bajo"
  },
  {
    "id": "pd9",
    "source": "planeta-digital",
    "name": "LENOVO IDEAPAD 3 SLIM I3-13VA TOUCH 15IRU8",
    "specs": "Coprocesador de gráficos Intel UHD Graphics · Marca del procesador Intel · Tipo de procesador Intel Core i3 13va · Velocidad del procesador 4,5GHz · Marca de la tarjeta gráfica Intel · Tamaño de RAM ‎8",
    "price": 399.0,
    "image": "imagenes/20-lenovo-ideapad-3-slim-i3-13va-touch-15iru8.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/71nl05XKNbL._AC_SX522.jpg?v=1721162141",
    "url": "https://planetadigitalec.com/products/lenovo-ideapad-3-slim-i3-13va-8gb-ram-256gb-ssd-win-11-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd10",
    "source": "planeta-digital",
    "name": "HP 15 I3-13VA",
    "specs": "Tarjeta de video: Intel® UHD Graphics integrada · Memoria RAM: 8 GB DDR4 (rendimiento fluido para navegación, ofimática y multitarea básica) · Almacenamiento: 256 GB SSD PCIe® NVMe (arranque rápido y buena capacidad para uso diario) · Pantalla · Sistema operativo: Windows 11 Home · USB-C (solo datos)",
    "price": 399.99,
    "image": "imagenes/21-hp-15-i3-13va.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/617pp3O9rxL._AC_SL1280.jpg?v=1778522484",
    "url": "https://planetadigitalec.com/products/hp-15-i3-n305-128gb-ssd-4gb-ram-touch-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd11",
    "source": "planeta-digital",
    "name": "ACER SPIN I3-12VA",
    "specs": "Coprocesador de gráficos Intel UHD Graphics · Interfaz de la unidad de disco duro USB 3.0 · Procesador ‎3,8 GHz apple core i3 _ 12va · Marca Chipset ‎Intel · Marca del procesador Intel · RAM ‎8 GB Lpddr 5",
    "price": 420.0,
    "image": "imagenes/22-acer-spin-i3-12va.png",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/descarga_64dcc938-3d00-428a-b4b9-11ed8b73182f.png?v=1740076331",
    "url": "https://planetadigitalec.com/products/acer-spin-i3-12va-8gb-ram-256gb-ssd-touch-windows-11-14",
    "badge": "Precio bajo"
  },
  {
    "id": "pd12",
    "source": "planeta-digital",
    "name": "DELL CORE 3 100U",
    "specs": "Intel® UHD Graphics Integrada · Procesador · Intel® Core™ i3-100U · Caché Intel Smart Cache · Memoria RAM · Memoria compartida con la RAM",
    "price": 420.0,
    "image": "imagenes/23-dell-core-3-100u.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/71d6CcN8Q5L._AC_SX466.jpg?v=1784063615",
    "url": "https://planetadigitalec.com/products/dell-core-3-100u-8gb-ram-512gb-ssd-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd13",
    "source": "planeta-digital",
    "name": "ASUS VIVOBOOK I5-13VA",
    "specs": "Procesador · Intel Core i5-1334U (hasta 4.6 GHz, 12 MB caché) · Gráficos Intel integrados · Memoria RAM · Almacenamiento · 256 GB SSD",
    "price": 460.0,
    "image": "imagenes/24-asus-vivobook-i5-13va.png",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/descarga-4-2-2048x2048.png?v=1766863433",
    "url": "https://planetadigitalec.com/products/asus-vivobook-i5-13va-12gb-256b-14",
    "badge": "Precio bajo"
  },
  {
    "id": "pd14",
    "source": "planeta-digital",
    "name": "HP Pavilion 16'',",
    "specs": "8 GB LPDDR5 RAM, 512 GB PCIe Gen4 NVMe M.2 unidad de estado sólido · Windows 11 Home, procesador AMD Ryzen 5 8540U, gráficos AMD Radeon · Cámara IR FHD con obturador, tecla de silencio del micrófono · Portátil HP Pavilion de 16\" con pantalla IPS micro-borde, anti-reflejo · Tarjeta inalámbrica Wi-Fi 6 y Bluetooth 5.3 · HP Pavilion 16-ag0052wm",
    "price": 479.75,
    "image": "imagenes/25-hp-pavilion-16.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/HP-Pavilion-16-inch-Windows-Laptop-AMD-Ryzen-5-8540U-AI-PC-8GB-RAM-512GB-SSD-Meteor-Silver_4c5b41b3-eff8-48e9-8b1a-658f1180b415.aaf6b4d4f1aeddec4545db00020721b3.jpg?v=1756842099",
    "url": "https://planetadigitalec.com/products/hp-pavilion-16-amd-ryzen-5-8540u-ai-pc-8gb-ram-512gb-ssd",
    "badge": "Precio bajo"
  },
  {
    "id": "pd15",
    "source": "planeta-digital",
    "name": "HP ENVY",
    "specs": "Procesador ‎2,3 GHz amd_r_series · Coprocesador de gráficos AMD · Marca Chipset ‎AMD · Marca del procesador AMD · RAM 8GB DDR4 · Tamaño de RAM de la tarjeta gráfica ‎8 GB",
    "price": 489.99,
    "image": "imagenes/26-hp-envy.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/61SxOcEECgL._AC_SL1500_29484842-8ff8-4d2b-8ee2-95d2a6244ebd.jpg?v=1713558068",
    "url": "https://planetadigitalec.com/products/hp-envy-ryzen-5-5500-8gb-ram-512gb-ssd-windows-11-touch-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd16",
    "source": "planeta-digital",
    "name": "HP ENVY",
    "specs": "Memoria: 8 GB LPDDR4x-4266 MHz RAM (integrada) - Disco duro: 256GB PCIe NVMe M.2 SSD · Inicio de Windows 11 · 2 USB tipo C de supervelocidad · 2 USB SuperSpeed tipo A · 1 HDMI 2.1 · HP ENVY X360 TOUCH 15-FH0013DX",
    "price": 499.0,
    "image": "imagenes/27-hp-envy.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/611zdkfj20L._AC_SL1500_1d4803c1-ca11-4d12-a927-519ebce5cf01.jpg?v=1713646377",
    "url": "https://planetadigitalec.com/products/hp-envy-ryzen-5-7000-8gb-ram-512gb-ssd-windows-11-touch-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd17",
    "source": "planeta-digital",
    "name": "LENOVO FLEX 5I I5-13VA",
    "specs": "Processor: Intel® Core™ i5-1335U, 10C (2P + 8E) · Graphics: Integrated Intel® Iris® Xe Graphics · Storage: 512GB SSD M.2 2242 PCIe® 4.0×4 NVMe® · Display: 16″(1920×1200) IPS 300nits Glossy, 45% NTSC · Camera: FHD 1080p with Privacy Shutter · OS: Windows® 11 Home + Office Home & Student 2021",
    "price": 499.75,
    "image": "imagenes/28-lenovo-flex-5i-i5-13va.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/51c0FVw9cQL._AC_SX466.jpg?v=1775687335",
    "url": "https://planetadigitalec.com/products/lenovo-flex-5i-i5-13va-8gb-ram-512gb-ssd-touch-16",
    "badge": "Precio bajo"
  },
  {
    "id": "pd18",
    "source": "planeta-digital",
    "name": "HP OMNIBOOK 5",
    "specs": "Familia del procesador · Procesador AMD Ryzen™ 5 · Procesador · SoC integrado AMD · Gráficos AMD Radeon™ 740M 3 · Almacenamiento interno",
    "price": 529.99,
    "image": "imagenes/29-hp-omnibook-5.png",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/25C1_OmniBook5_16_GlacierSilver_T_NT_IRCam_nonFPR_Win11_CoreSet_Front_TransparentBG_3378800.png?v=1765232732",
    "url": "https://planetadigitalec.com/products/hp-omnibook-5-ryzen-5-8540-u-8-gb-ram-512gb-ssd-16",
    "badge": "Precio bajo"
  },
  {
    "id": "pd19",
    "source": "planeta-digital",
    "name": "ASUS VIVOBOOK GO",
    "specs": "Memoria RAM: 12GB LPDDR5 en placa capacidad máxima · Tarjeta de vídeo: AMD Radeon™ Graphics Integrados · Almacenamiento: SSD M.2 NVMe™ PCIe® 3.0 de 512 GB · Pantalla: 15,6 pulgadas, FHD (1920 x 1080) 16: 9 · 1x USB 2.0 tipo A · 1x USB 3.2 Gen 1 Tipo A",
    "price": 530.0,
    "image": "imagenes/30-asus-vivobook-go.png",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/descarga-4-550x550.png?v=1721323710",
    "url": "https://planetadigitalec.com/products/asus-vivobook-go-ryzen-5-7500u-16gb-ram-512gb-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd20",
    "source": "planeta-digital",
    "name": "LENOVO IDEAPAD SLIM 3",
    "specs": "Procesador · AMD Radeon™ 610M Graphics Integrada · Memoria RAM · Almacenamiento · 512 GB SSD NVMe PCIe® (arranque rápido, excelente velocidad de lectura y escritura) · Compatible con reproducción de video en alta resolución",
    "price": 530.0,
    "image": "imagenes/31-lenovo-ideapad-slim-3.png",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/lenovo-ideapad-slim-3-15amn8-frente-pantalla-fhd-tn-color-arctic-grey-cemco.webp?v=1782339257",
    "url": "https://planetadigitalec.com/products/lenovo-ideapad-slim-3-ryzen-5-7520u-8gb-ram-512gb-ssd-16",
    "badge": "Precio bajo"
  },
  {
    "id": "pd21",
    "source": "planeta-digital",
    "name": "LENOVO IDEAPAD SLIM 3 - I5-13VA",
    "specs": "Tarjeta Gráfica Intel® Iris® Xe Graphics · Memoria RAM 8 GB de RAM · Disco Duro 512GB M.2 2242 PCIe® 4.0 x4 (Disco Sólido – SSD) · Pantalla · Pantalla de 16″ WUXGA (1920×1200). IPS, 120Hz · Sistema Operativo Windows 11",
    "price": 549.95,
    "image": "imagenes/32-lenovo-ideapad-slim-3---i5-13va.png",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/lenovo-ideapad-slim-5-16iah8-83bg001xvn-chinh-hang-2.webp?v=1711056201",
    "url": "https://planetadigitalec.com/products/lenovo-ideapad-slim-5-i5-13va-8gb-ram-512gb-ssd-16",
    "badge": "Precio bajo"
  },
  {
    "id": "pd22",
    "source": "planeta-digital",
    "name": "ASUS VIVOBOOK I5 - 13VA",
    "specs": "Gráficos Gráficos Intel® · Almacenamiento 512Gb SSD M.2 2280 NVMe™ PCIe® 4.0, x4 · Pantalla · Wi-Fi 6E (802.11ax) (banda dual) 1*1 · 1x USB 2.0 Tipo-A (velocidad de datos de hasta 480Mbps) · 1x USB 3.2 Gen 1 Tipo-C (velocidad de datos de hasta 5Gbps)",
    "price": 550.0,
    "image": "imagenes/33-asus-vivobook-i5---13va.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/4_54.webp?v=1760652065",
    "url": "https://planetadigitalec.com/products/asus-vivobook-i5-13va-16-gb-1tb-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd23",
    "source": "planeta-digital",
    "name": "HP I5-13VA",
    "specs": "Coprocesador de gráficos Intel UHD Graphics · Procesador ‎1,3 GHz core_i5_13VA · Marca Chipset ‎Intel · Marca del procesador Intel · RAM ‎12 GB SO-DIMM · Disco Duro ‎512 GB SSD PCIe NVMe",
    "price": 599.0,
    "image": "imagenes/34-hp-i5-13va.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/612KwwQKUGL._AC_SX355.jpg?v=1744841525",
    "url": "https://planetadigitalec.com/products/hp-i5-13va-16gb-ram-512gb-ssd-windows-11",
    "badge": "Precio bajo"
  },
  {
    "id": "pd24",
    "source": "planeta-digital",
    "name": "LENOVO IDEAPA SLIM 3 I5-13VA",
    "specs": "Máxima resolución de pantalla ‎1920x1080 MP · Procesador ‎4.6 GHz core_i5_13va · Marca Chipset ‎Intel · Marca del procesador ‎Intel · RAM ‎16 GB SDRAM · Tamaño de RAM de la tarjeta gráfica ‎1.00",
    "price": 599.0,
    "image": "imagenes/35-lenovo-ideapa-slim-3-i5-13va.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/51Iym2s47NL._AC_SY355.jpg?v=1732570485",
    "url": "https://planetadigitalec.com/products/lenovo-ideapa-slim-3-i5-13va-16gb-ram-512gb-ssd-touch-15-6",
    "badge": "Precio bajo"
  },
  {
    "id": "pd25",
    "source": "planeta-digital",
    "name": "HP OMNIBOOK FLIP",
    "specs": "procesador: AMD Ryzen™ 5 220 (hasta 4,9 GHz, 16 MB de caché L3, 6 núcleos) · Coprocesador de gráficos Gráficos AMD Radeon 740M · Marca Chipset ‎AMD · Marca del procesador AMD · RAM ‎8 GB Lpddr 5 · Disco duro ‎512 GB SSD",
    "price": 599.77,
    "image": "imagenes/36-hp-omnibook-flip.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/61IFZawdmdL._AC_SX466.jpg?v=1756748995",
    "url": "https://planetadigitalec.com/products/hp-omnibook-flip-ryzen-5-220w-ai-8gb-ram-512gb-ssd-16",
    "badge": "Precio bajo"
  },
  {
    "id": "pd26",
    "source": "planeta-digital",
    "name": "MSI CLAW GAMING HANDHELD ULTRA 7-155H",
    "specs": "Procesador ‎1,4 GHz Intel_Mobile_CPU · Marca Chipset ‎Intel · Marca del procesador Intel · RAM ‎16GB LPDDR5 · Tipo de memoria del equipo ‎DDR5 RAM · Disco Duro 512 GB SSD",
    "price": 620.0,
    "image": "imagenes/37-msi-claw-gaming-handheld-ultra-7-155h.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/510WjZAovxL._AC_SX466.jpg?v=1755290289",
    "url": "https://planetadigitalec.com/products/msi-claw-gaming-handheld-ultra-7-155h-7-120hz-fhd-16gb-ram-512gb-ssd",
    "badge": "Precio bajo"
  },
  {
    "id": "pd27",
    "source": "planeta-digital",
    "name": "Lenovo V15,",
    "specs": "Procesador · AMD Ryzen™ 7 7730U (4,5 GHz Max Boost, 16MB Cache, 8 núcleos y 16 subprocesos) · Tarjeta de video: AMD Radeon™ Graphics · Ram: 16GB DDR5 · Almacenamiento 512GB SSD M.2 · Pantalla",
    "price": 629.0,
    "image": "imagenes/38-lenovo-v15.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/81aQUyiv4iL._AC_SX466.jpg?v=1731620120",
    "url": "https://planetadigitalec.com/products/lenovo-v15-ryzen-7-7730u-16gb-512gb-ssd",
    "badge": "Precio bajo"
  },
  {
    "id": "pd28",
    "source": "planeta-digital",
    "name": "LENOVO YOGA 7 I5-13VA",
    "specs": "Coprocesador de gráficos Intel UHD Graphics 620 · Resolución máxima de pantalla 1920x1200 MP · Procesador ‎4,6 GHz core_i5_13VA · Marca Chipset ‎Intel · Marca del procesador Intel · Memoria RAM 8 GB SDRAM",
    "price": 630.0,
    "image": "imagenes/39-lenovo-yoga-7-i5-13va.jpg",
    "image_remote": "https://cdn.shopify.com/s/files/1/2308/0861/files/51OlGWavS2L._AC_SX466.jpg?v=1748113770",
    "url": "https://planetadigitalec.com/products/lenovo-yoga-7-i5-13va-8gb-ram-512gbssd-windows-11-x360-touch-16",
    "badge": "Precio bajo"
  },
  {
    "id": "m1",
    "source": "mundotek",
    "name": "Infinix SMART 6 HD",
    "specs": "Infinix SMART 6 HD Ram 2GB- 32GB",
    "price": 69.0,
    "image": "imagenes/40-infinix-smart-6-hd.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/infinix-smart-6-hd-azul.webp",
    "url": "https://mundotek.com.ec/producto/infinix-smart-6-hd-ram-2gb-32gb/",
    "badge": "#1 más económico"
  },
  {
    "id": "m2",
    "source": "mundotek",
    "name": "Xiaomi 15 Ultra",
    "specs": "Smartphone · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 99.0,
    "image": "imagenes/41-xiaomi-15-ultra.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/kit15.webp",
    "url": "https://mundotek.com.ec/producto/kit-fotografico-del-xiaomi-15-ultra/",
    "badge": "Precio bajo"
  },
  {
    "id": "m3",
    "source": "mundotek",
    "name": "Realme C21Y Ram4GB/64GB",
    "specs": "Realme C21Y Ram4GB/64GB",
    "price": 99.0,
    "image": "imagenes/42-realme-c21y-ram4gb-64gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/rmc21y-464gb-blu-9-1000x1000-1.jpg",
    "url": "https://mundotek.com.ec/producto/realme-c21y-ram4gb-64gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m4",
    "source": "mundotek",
    "name": "Realme C11 (2021)",
    "specs": "Realme C11 (2021) RAM 2GB/32GB",
    "price": 102.0,
    "image": "imagenes/43-realme-c11-2021.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/07/Realme-C11.jpg",
    "url": "https://mundotek.com.ec/producto/realme-c11/",
    "badge": "Precio bajo"
  },
  {
    "id": "m5",
    "source": "mundotek",
    "name": "Infinix Hot 20i",
    "specs": "Infinix Hot 20i RAM 4+3 GB 128GB",
    "price": 129.0,
    "image": "imagenes/44-infinix-hot-20i.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/hot-20i.webp",
    "url": "https://mundotek.com.ec/producto/infinix-hot-20i-ram-43-gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m6",
    "source": "mundotek",
    "name": "Tecno Spark Go 3 Ram4+4GB-128GB",
    "specs": "Tecno Spark Go 3 Ram4+4GB-128GB",
    "price": 135.0,
    "image": "imagenes/45-tecno-spark-go-3-ram4-4gb-128gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/tecno-spark-go-3.webp",
    "url": "https://mundotek.com.ec/producto/tecno-spark-go-3-ram44gb-64gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m7",
    "source": "mundotek",
    "name": "Logic G1L GAMING PHONE+GAME PAD+BUDS",
    "specs": "LOGIC G1L GAMING PHONE+GAME PAD+BUDS RAM 4+10GB · 128GB",
    "price": 139.0,
    "image": "imagenes/46-logic-g1l-gaming-phone-game-pad-buds.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/08/logi.png",
    "url": "https://mundotek.com.ec/producto/logic-g1l-gaming-phonegame-padbuds-ram-410gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m8",
    "source": "mundotek",
    "name": "Samsung A07",
    "specs": "Samsung A07 Ram 4GB- 128GB",
    "price": 139.0,
    "image": "imagenes/47-samsung-a07.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/a07.webp",
    "url": "https://mundotek.com.ec/producto/samsung-a07-ram-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m9",
    "source": "mundotek",
    "name": "Infinix smart 20",
    "specs": "Infinix Smart 20 Ram 4 +4 GB -128GB-256GB",
    "price": 139.0,
    "image": "imagenes/48-infinix-smart-20.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/infinix-smart-20.jpg",
    "url": "https://mundotek.com.ec/producto/infinix-smart-20-ram-4-4-gb-64gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m10",
    "source": "mundotek",
    "name": "Xiaomi Redmi A7 Pro",
    "specs": "Xiaomi Redmi A7 Pro Ram 4GB-128GB",
    "price": 145.0,
    "image": "imagenes/49-xiaomi-redmi-a7-pro.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/xiaomi-redmi-a7-pro.webp",
    "url": "https://mundotek.com.ec/producto/xiaomi-redmi-a7-pro-ram-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m11",
    "source": "mundotek",
    "name": "Motorola G06",
    "specs": "MOTOROLA G06 Ram 4GB+4GB-256GB",
    "price": 149.0,
    "image": "imagenes/50-motorola-g06.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/g06.jpeg",
    "url": "https://mundotek.com.ec/producto/motorola-g06-ram-4gb4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m12",
    "source": "mundotek",
    "name": "Tcl L10+",
    "specs": "TCL L10+",
    "price": 150.0,
    "image": "imagenes/51-tcl-l10.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/04/1062.jpg",
    "url": "https://mundotek.com.ec/producto/l10/",
    "badge": "Precio bajo"
  },
  {
    "id": "m13",
    "source": "mundotek",
    "name": "Oppo A5 4G",
    "specs": "OPPO A5 4G RAM 4GB-256GB",
    "price": 165.0,
    "image": "imagenes/52-oppo-a5-4g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/a5-4g.png",
    "url": "https://mundotek.com.ec/producto/oppo-a5-4g-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m14",
    "source": "mundotek",
    "name": "Tecno Spark 9 Pro",
    "specs": "Tecno Spark 9 Pro",
    "price": 175.0,
    "image": "imagenes/53-tecno-spark-9-pro.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/11/Tecno-Spark-9-Pro-4.jpg",
    "url": "https://mundotek.com.ec/producto/tecno-spark-9-pro/",
    "badge": "Precio bajo"
  },
  {
    "id": "m15",
    "source": "mundotek",
    "name": "Motorola G17",
    "specs": "Motorola G17 Ram 4GB- 256GB",
    "price": 185.0,
    "image": "imagenes/54-motorola-g17.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/moto-g17.jpg",
    "url": "https://mundotek.com.ec/producto/motorola-g17-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m16",
    "source": "mundotek",
    "name": "Xiaomi Redmi 15c",
    "specs": "Xiaomi Redmi 15c Ram 8gb · 256gb",
    "price": 189.0,
    "image": "imagenes/55-xiaomi-redmi-15c.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/redmi15c.webp",
    "url": "https://mundotek.com.ec/producto/xiaomi-redmi-15c-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m17",
    "source": "mundotek",
    "name": "Realme Narzo 30 (5G)",
    "specs": "Realme Narzo 30 (5G)",
    "price": 195.0,
    "image": "imagenes/56-realme-narzo-30-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/11/719tm7l723L._SL1500_.jpg",
    "url": "https://mundotek.com.ec/producto/realme-narzo-30-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "m18",
    "source": "mundotek",
    "name": "Zte Nubia V80 Max",
    "specs": "ZTE Nubia V80 Max Ram 8+12 GB-256GB",
    "price": 199.0,
    "image": "imagenes/57-zte-nubia-v80-max.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/zte-v80-max.jpg",
    "url": "https://mundotek.com.ec/producto/zte-nubia-v80-max-ram-812-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m19",
    "source": "mundotek",
    "name": "Motorola G56 5G",
    "specs": "MOTOROLA G56 5G 8GB+8GB-256GB",
    "price": 229.0,
    "image": "imagenes/58-motorola-g56-5g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/12/moto-56.png",
    "url": "https://mundotek.com.ec/producto/motorola-g56-5g-8gb8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m20",
    "source": "mundotek",
    "name": "Samsung Galaxy A17",
    "specs": "SAMSUNG GALAXY A17 8GB -256GB Androir",
    "price": 259.0,
    "image": "imagenes/59-samsung-galaxy-a17.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/sam-a17-4g.webp",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a17-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m21",
    "source": "mundotek",
    "name": "Xiaomi Mi 10 lite",
    "specs": "Xiaomi Mi 10 lite 128gb 6gb Ram 5G",
    "price": 269.0,
    "image": "imagenes/60-xiaomi-mi-10-lite.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/01/1-15.svg",
    "url": "https://mundotek.com.ec/producto/xiaomi-mi-10-lite-128gb-6gb-ram-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "m22",
    "source": "mundotek",
    "name": "Oppo A5 5G",
    "specs": "OPPO A5 5G Ram 8GB · 256GB",
    "price": 269.0,
    "image": "imagenes/61-oppo-a5-5g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/oppoa5.png",
    "url": "https://mundotek.com.ec/producto/oppo-a5-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m23",
    "source": "mundotek",
    "name": "Tecno camon 18 premier",
    "specs": "Tecno camon 18 premier",
    "price": 315.0,
    "image": "imagenes/62-tecno-camon-18-premier.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/04/camon-.jpg",
    "url": "https://mundotek.com.ec/producto/tecno-camon-18-premier/",
    "badge": "Precio bajo"
  },
  {
    "id": "m24",
    "source": "mundotek",
    "name": "Honor X8d",
    "specs": "HONOR X8d Ram 8GB- 256GB/512GB",
    "price": 319.0,
    "image": "imagenes/63-honor-x8d.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/honor-x8d.webp",
    "url": "https://mundotek.com.ec/producto/honor-x8d-ram-8gb-256gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m25",
    "source": "mundotek",
    "name": "Realme P3 5G",
    "specs": "Realme P3 5G RAM 8GB/12GB- 256GB/512GB +control",
    "price": 329.0,
    "image": "imagenes/64-realme-p3-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/09/realmemas-control.jpg",
    "url": "https://mundotek.com.ec/producto/realme-p3-5g-ram-8gb-12gb-256gb-512gb-control/",
    "badge": "Precio bajo"
  },
  {
    "id": "m26",
    "source": "mundotek",
    "name": "Tecno Camón 50 pro",
    "specs": "Tecno Camón 50 pro Ram 8+8 GB/256GB+audifonos tipo diadema",
    "price": 339.0,
    "image": "imagenes/65-tecno-cam-n-50-pro.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/camon-con-audifonos.png",
    "url": "https://mundotek.com.ec/producto/tecno-camon-50-pro-ram-88-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m27",
    "source": "mundotek",
    "name": "Xiaomi Poco F4",
    "specs": "XIAOMI POCO F4 Ram 8GB · 256GB",
    "price": 399.0,
    "image": "imagenes/66-xiaomi-poco-f4.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/08/Nuevo-proyecto-11-1.png",
    "url": "https://mundotek.com.ec/producto/xiaomi-poco-f4-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m28",
    "source": "mundotek",
    "name": "Samsung Galaxy A37 5G",
    "specs": "Samsung Galaxy A37 5G Ram 8GB- 256GB",
    "price": 399.0,
    "image": "imagenes/67-samsung-galaxy-a37-5g.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/a37.webp",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a37-5g-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m29",
    "source": "mundotek",
    "name": "Honor Magic8 Lite",
    "specs": "Honor Magic8 Lite Ram 8GB/256GB",
    "price": 409.0,
    "image": "imagenes/68-honor-magic8-lite.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/01/magi-8lite.webp",
    "url": "https://mundotek.com.ec/producto/honor-magic8-lite-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m30",
    "source": "mundotek",
    "name": "Motorola Edge 70 Fusion",
    "specs": "Motorola Edge 70 Fusion Ram 8GB-256GB +Buds motorola",
    "price": 419.0,
    "image": "imagenes/69-motorola-edge-70-fusion.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/70-fushion.png",
    "url": "https://mundotek.com.ec/producto/motorola-edge-70-fusion-ram-8gb-256gb-buds-motorola/",
    "badge": "Precio bajo"
  },
  {
    "id": "m31",
    "source": "mundotek",
    "name": "Tecno CAMON 50 Ultra 5G",
    "specs": "TECNO CAMON 50 Ultra 5G Ram 8+8GB – 256GB",
    "price": 429.0,
    "image": "imagenes/70-tecno-camon-50-ultra-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/camon-50-ultra-1.jpg",
    "url": "https://mundotek.com.ec/producto/tecno-camon-50-ultra-5g-ram-88gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m32",
    "source": "mundotek",
    "name": "Samsung Galaxy A56 5G",
    "specs": "Samsung Galaxy A56 5G Ram 12GB · 256GB",
    "price": 439.0,
    "image": "imagenes/71-samsung-galaxy-a56-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/a56.jpg",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a56-5g-ram-12gb-256gb-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "m33",
    "source": "mundotek",
    "name": "Honor 600E",
    "specs": "Honor 600E Ram 8GB-256GB",
    "price": 449.0,
    "image": "imagenes/72-honor-600e.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/honor-e.webp",
    "url": "https://mundotek.com.ec/producto/honor-600e-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m34",
    "source": "mundotek",
    "name": "Samsung Galaxy A57",
    "specs": "Samsung Galaxy A57 Ram 8GB-256GB IA",
    "price": 469.0,
    "image": "imagenes/73-samsung-galaxy-a57.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/a57.png",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a57-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m35",
    "source": "mundotek",
    "name": "Xiaomi Redmi Note 15 Pro Plus 5G",
    "specs": "Redmi Note 15 Pro Plus 5G Ram 12GB- 512GB",
    "price": 489.0,
    "image": "imagenes/74-redmi-note-15-pro-plus-5g.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/xiaomi-redmi-note15-pro-plus.png",
    "url": "https://mundotek.com.ec/producto/redmi-note-15-pro-plus-5g-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m36",
    "source": "mundotek",
    "name": "Oppo Reno13F 5G",
    "specs": "Oppo Reno13F 5G Ram 12GB · 512GB IP69",
    "price": 499.0,
    "image": "imagenes/75-oppo-reno13f-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/reno-13f.jpg",
    "url": "https://mundotek.com.ec/producto/reno13-f-5g-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m37",
    "source": "mundotek",
    "name": "Oppo Reno14F",
    "specs": "Oppo Reno14F Ram 12GB-512GB +AUDIFONOS",
    "price": 535.0,
    "image": "imagenes/76-oppo-reno14f.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/01/reno.webp",
    "url": "https://mundotek.com.ec/producto/oppo-reno14f-ram-12gb-512gb-audifonos/",
    "badge": "Precio bajo"
  },
  {
    "id": "m38",
    "source": "mundotek",
    "name": "Xiaomi Poco x8 Pro",
    "specs": "Xiaomi Poco x8 Pro Ram 12GB · 512GB",
    "price": 569.0,
    "image": "imagenes/77-xiaomi-poco-x8-pro.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/x8-pro.jpg",
    "url": "https://mundotek.com.ec/producto/xiaomi-poco-x8-pro-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m39",
    "source": "mundotek",
    "name": "Apple iPhone 11 PRO MAX OPEN BOX A",
    "specs": "IPHONE 11 PRO MAX OPEN BOX A 256GB",
    "price": 579.0,
    "image": "imagenes/78-iphone-11-pro-max-open-box-a.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/09/11-pro-max-p.jpg",
    "url": "https://mundotek.com.ec/producto/iphone-11-pro-max-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "m40",
    "source": "mundotek",
    "name": "Infinix GT 50 Pro HydroFlow y gatillos laterales",
    "specs": "Infinix GT 50 Pro HydroFlow y gatillos laterales Ram 12+12 GB-256GB",
    "price": 599.0,
    "image": "imagenes/79-infinix-gt-50-pro-hydroflow-y-gatillos-laterales.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/07/infinix-gt-50-pro-launched-in-ph-c.jpg",
    "url": "https://mundotek.com.ec/producto/infinix-gt-50-pro-hydroflow-y-gatillos-laterales-ram-1212-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m41",
    "source": "mundotek",
    "name": "Honor 600",
    "specs": "HONOR 600 Ram 8GB-256GB",
    "price": 659.0,
    "image": "imagenes/80-honor-600.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/honor-600.webp",
    "url": "https://mundotek.com.ec/producto/honor-600-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag1",
    "source": "alta-gama",
    "name": "OnePlus Nord N200 5G – Open box",
    "specs": "Nord N200 5G – Open box",
    "price": 90.0,
    "image": "imagenes/81-nord-n200-5g-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/09/One-Plus-N200-5G.png",
    "url": "https://altagamastore.ec/producto/nord-n200-5g/",
    "badge": "#1 más económico"
  },
  {
    "id": "ag2",
    "source": "alta-gama",
    "name": "Honor play 10/",
    "specs": "Honor Play 10",
    "price": 115.0,
    "image": "imagenes/82-honor-play-10.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/06/Honor-Play-10-1.png",
    "url": "https://altagamastore.ec/producto/honor-play-10/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag3",
    "source": "alta-gama",
    "name": "Blackview BV4800 Pro",
    "specs": "BV4800 Pro",
    "price": 125.0,
    "image": "imagenes/83-bv4800-pro.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/08/BKACKVIEW-BV4800-NEGRO.png",
    "url": "https://altagamastore.ec/producto/bv4800/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag4",
    "source": "alta-gama",
    "name": "Samsung Galaxy A16 – Open Box",
    "specs": "Galaxy A16 – Open Box",
    "price": 150.0,
    "image": "imagenes/84-galaxy-a16-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/02/IMG_3845.png",
    "url": "https://altagamastore.ec/producto/galaxy-a16-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag5",
    "source": "alta-gama",
    "name": "Motorola G17",
    "specs": "Motorola G17",
    "price": 170.0,
    "image": "imagenes/85-motorola-g17.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/08/MOTOROLA-G17-AZUL.png",
    "url": "https://altagamastore.ec/producto/motorola-g17/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag6",
    "source": "alta-gama",
    "name": "Xiaomi Redmi 15C 4G",
    "specs": "Redmi 15C 4G",
    "price": 190.0,
    "image": "imagenes/86-redmi-15c-4g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/08/REDMI-15C-AZUL.png",
    "url": "https://altagamastore.ec/producto/redmi-15c/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag7",
    "source": "alta-gama",
    "name": "Honor X6C",
    "specs": "Honor X6C",
    "price": 190.0,
    "image": "imagenes/87-honor-x6c.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/07/HONOR-X6C-NEGRO-8.png",
    "url": "https://altagamastore.ec/producto/honor-x6c-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag8",
    "source": "alta-gama",
    "name": "Samsung Galaxy A17",
    "specs": "Galaxy A17",
    "price": 190.0,
    "image": "imagenes/88-galaxy-a17.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/11/GALAXY-A17-4G-NEGRO.png",
    "url": "https://altagamastore.ec/producto/galaxy-a17-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag9",
    "source": "alta-gama",
    "name": "Samsung Galaxy A54 – Open Box",
    "specs": "Galaxy A54 – Open Box",
    "price": 195.0,
    "image": "imagenes/89-galaxy-a54-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/A54-NEGRO.png",
    "url": "https://altagamastore.ec/producto/open-box-samsung-galaxy-a54/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag10",
    "source": "alta-gama",
    "name": "OPPO A6C",
    "specs": "A6C",
    "price": 205.0,
    "image": "imagenes/90-a6c.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/08/OPPO-A6C-BLANCO.png",
    "url": "https://altagamastore.ec/producto/a6c/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag11",
    "source": "alta-gama",
    "name": "Xiaomi Redmi Note 15 4G",
    "specs": "Redmi Note 15 4G",
    "price": 220.0,
    "image": "imagenes/91-redmi-note-15-4g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/01/remi-note-15-4g-negro.png",
    "url": "https://altagamastore.ec/producto/redmi-note-15-4g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag12",
    "source": "alta-gama",
    "name": "Motorola G56",
    "specs": "Moto G56",
    "price": 225.0,
    "image": "imagenes/92-moto-g56.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/03/MOTO-G56-AZUL-1.png",
    "url": "https://altagamastore.ec/producto/moto-g56/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag13",
    "source": "alta-gama",
    "name": "Xiaomi Redmi Note 15 NFC",
    "specs": "Redmi Note 15 NFC",
    "price": 225.0,
    "image": "imagenes/93-redmi-note-15-nfc.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/01/remi-note-15-4g-negro.png",
    "url": "https://altagamastore.ec/producto/redmi-note-15-4g-nfc/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag14",
    "source": "alta-gama",
    "name": "Honor X7D",
    "specs": "Honor X7D",
    "price": 230.0,
    "image": "imagenes/94-honor-x7d.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/12/HONOR-X7D-PLATA.png",
    "url": "https://altagamastore.ec/producto/honor-x7d-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag15",
    "source": "alta-gama",
    "name": "Xiaomi Redmi Note 14 Pro 4G",
    "specs": "Redmi Note 14 Pro 4G",
    "price": 265.0,
    "image": "imagenes/95-redmi-note-14-pro-4g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-19-2.png",
    "url": "https://altagamastore.ec/producto/redmi-note-14-pro-4g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag16",
    "source": "alta-gama",
    "name": "Apple iPhone 12 – Open Box",
    "specs": "iPhone 12 – Open Box",
    "price": 275.0,
    "image": "imagenes/96-iphone-12-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-4-1.png",
    "url": "https://altagamastore.ec/producto/iphone-12-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag17",
    "source": "alta-gama",
    "name": "Samsung Galaxy S22 5G – Open Box",
    "specs": "Galaxy S22 5G – Open Box",
    "price": 280.0,
    "image": "imagenes/97-galaxy-s22-5g-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-52-1.png",
    "url": "https://altagamastore.ec/producto/samsung-galaxy-s22-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag18",
    "source": "alta-gama",
    "name": "Samsung Galaxy A26 5G",
    "specs": "Galaxy A26 5G",
    "price": 290.0,
    "image": "imagenes/98-galaxy-a26-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/SAMSUNG-A26-NEGRO.png",
    "url": "https://altagamastore.ec/producto/galaxy-a26-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag19",
    "source": "alta-gama",
    "name": "Xiaomi Redmi Note 15 5G",
    "specs": "Redmi Note 15 5G",
    "price": 290.0,
    "image": "imagenes/99-redmi-note-15-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/03/Redmi-note-15-pro-5g-morado-niebla.png",
    "url": "https://altagamastore.ec/producto/redmi-note-15-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag20",
    "source": "alta-gama",
    "name": "Xiaomi Redmi Note 15 Pro 4G",
    "specs": "Redmi Note 15 Pro 4G",
    "price": 295.0,
    "image": "imagenes/100-redmi-note-15-pro-4g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/01/redmi-note-15-pro-negro.png",
    "url": "https://altagamastore.ec/producto/redmi-note-15-pro-4g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag21",
    "source": "alta-gama",
    "name": "OPPO A6X",
    "specs": "A6X",
    "price": 295.0,
    "image": "imagenes/101-a6x.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/09/OPPO-A6X-NEGRO.png",
    "url": "https://altagamastore.ec/producto/a6x/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag22",
    "source": "alta-gama",
    "name": "Honor X8D",
    "specs": "Honor X8D",
    "price": 310.0,
    "image": "imagenes/102-honor-x8d.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/02/Honor-X8D-CELESTE-1.png",
    "url": "https://altagamastore.ec/producto/honor-x8d/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag23",
    "source": "alta-gama",
    "name": "Google Pixel 8 A- Open Box",
    "specs": "Pixel 8 A- Open Box",
    "price": 310.0,
    "image": "imagenes/103-pixel-8-a--open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/05/Pixel-8-Gris.png",
    "url": "https://altagamastore.ec/producto/pixel-8-a-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag24",
    "source": "alta-gama",
    "name": "Motorola Edge 60 Fusion",
    "specs": "Moto Edge 60 Fusion",
    "price": 315.0,
    "image": "imagenes/104-moto-edge-60-fusion.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/03/MOTO-EDGE-60-FUSION-AZUL-VIBRANTE.png",
    "url": "https://altagamastore.ec/producto/motorola-edge-60-fusion/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag25",
    "source": "alta-gama",
    "name": "Samsung Galaxy S22+ 5G – Open Box",
    "specs": "Galaxy S22+ 5G – Open Box",
    "price": 320.0,
    "image": "imagenes/105-galaxy-s22-5g-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-55-1.png",
    "url": "https://altagamastore.ec/producto/samsung-galaxy-s22/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag26",
    "source": "alta-gama",
    "name": "Xiaomi Redmi Note 14 Pro 5G",
    "specs": "Redmi Note 14 Pro 5G",
    "price": 320.0,
    "image": "imagenes/106-redmi-note-14-pro-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/02/REDMI-NOTE-14-PRO-5G-MORADO.png",
    "url": "https://altagamastore.ec/producto/redmi-note-14-pro-5g-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag27",
    "source": "alta-gama",
    "name": "Samsung Galaxy S23 5G – Open Box",
    "specs": "Galaxy S23 5G – Open Box",
    "price": 325.0,
    "image": "imagenes/107-galaxy-s23-5g-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/05/GALAXY-S23.png",
    "url": "https://altagamastore.ec/producto/galaxy-s23-5g-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag28",
    "source": "alta-gama",
    "name": "Samsung Galaxy S23 FE 5G – Open Box",
    "specs": "Galaxy S23 FE 5G – Open Box",
    "price": 335.0,
    "image": "imagenes/108-galaxy-s23-fe-5g-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/05/S23FE-MORADO.png",
    "url": "https://altagamastore.ec/producto/galaxy-s23fe-5g-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag29",
    "source": "alta-gama",
    "name": "Apple iPhone 13 – Open Box",
    "specs": "iPhone 13 – Open Box",
    "price": 340.0,
    "image": "imagenes/109-iphone-13-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-5-2.png",
    "url": "https://altagamastore.ec/producto/iphone-13-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag30",
    "source": "alta-gama",
    "name": "Apple iPhone 12 Pro – Open Box",
    "specs": "iPhone 12 Pro – Open Box",
    "price": 350.0,
    "image": "imagenes/110-iphone-12-pro-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-59.png",
    "url": "https://altagamastore.ec/producto/iphone-12-pro-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag31",
    "source": "alta-gama",
    "name": "Samsung Galaxy A36 5G",
    "specs": "Galaxy A36 5G",
    "price": 350.0,
    "image": "imagenes/111-galaxy-a36-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/SAMSUNG-A36-A56-AZUL.png",
    "url": "https://altagamastore.ec/producto/galaxy-a36-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag32",
    "source": "alta-gama",
    "name": "Xiaomi Poco X7 Pro 5G",
    "specs": "Poco X7 Pro 5G",
    "price": 350.0,
    "image": "imagenes/112-poco-x7-pro-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-17-2.png",
    "url": "https://altagamastore.ec/producto/poco-x7-pro-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag33",
    "source": "alta-gama",
    "name": "Google Pixel 8 – Open Box",
    "specs": "Pixel 8 – Open Box",
    "price": 350.0,
    "image": "imagenes/113-pixel-8-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-11-2.png",
    "url": "https://altagamastore.ec/producto/pixel-8-open-box-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag34",
    "source": "alta-gama",
    "name": "Samsung Galaxy S24 FE – Open Box",
    "specs": "Galaxy S24 FE – Open Box",
    "price": 360.0,
    "image": "imagenes/114-galaxy-s24-fe-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-1.png",
    "url": "https://altagamastore.ec/producto/galaxy-s24-fe-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag35",
    "source": "alta-gama",
    "name": "OPPO A6",
    "specs": "Smartphone · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 360.0,
    "image": "imagenes/115-a6.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/09/oppo-a6-azul.png",
    "url": "https://altagamastore.ec/producto/a6c-copia/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag36",
    "source": "alta-gama",
    "name": "Samsung Galaxy S23+ 5G – Open Box",
    "specs": "Galaxy S23+ 5G – Open Box",
    "price": 380.0,
    "image": "imagenes/116-galaxy-s23-5g-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/09/Galaxy-S23-Plus-Negro.png",
    "url": "https://altagamastore.ec/producto/galaxy-s23-plus-5g-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag37",
    "source": "alta-gama",
    "name": "Xiaomi Redmi Note 15 Pro 5G",
    "specs": "Redmi Note 15 Pro 5G",
    "price": 385.0,
    "image": "imagenes/117-redmi-note-15-pro-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/03/Redmi-Note-15-Pro-5g-Azul-1.png",
    "url": "https://altagamastore.ec/producto/redmi-note-15-pro-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag38",
    "source": "alta-gama",
    "name": "Google Pixel 8 Pro – Open Box",
    "specs": "Pixel 8 Pro – Open Box",
    "price": 390.0,
    "image": "imagenes/118-pixel-8-pro-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-11-2.png",
    "url": "https://altagamastore.ec/producto/pixel-8-pro-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag39",
    "source": "alta-gama",
    "name": "Honor Magic 8 Lite 5G",
    "specs": "Honor Magic 8 Lite 5G",
    "price": 400.0,
    "image": "imagenes/119-honor-magic-8-lite-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/01/Magic-8-lite-crema.png",
    "url": "https://altagamastore.ec/producto/honor-magic-8-lite-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag40",
    "source": "alta-gama",
    "name": "Google Pixel 9A – Open Box",
    "specs": "Pixel 9A – Open Box",
    "price": 400.0,
    "image": "imagenes/120-pixel-9a-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/06/Pixel-9A-Negro.png",
    "url": "https://altagamastore.ec/producto/pixel-9a-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag41",
    "source": "alta-gama",
    "name": "Apple iPhone 14 – Open Box",
    "specs": "iPhone 14 – Open Box",
    "price": 420.0,
    "image": "imagenes/121-iphone-14-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-6-1.png",
    "url": "https://altagamastore.ec/producto/iphone-14-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag42",
    "source": "alta-gama",
    "name": "Apple iPhone 12 Pro Max – Open Box",
    "specs": "iPhone 12 Pro Max – Open Box",
    "price": 425.0,
    "image": "imagenes/122-iphone-12-pro-max-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-60-1.png",
    "url": "https://altagamastore.ec/producto/iphone-12-pro-max-openbox/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag43",
    "source": "alta-gama",
    "name": "Motorola Edge 70 Fusion",
    "specs": "Moto Edge 70 Fusion",
    "price": 430.0,
    "image": "imagenes/123-moto-edge-70-fusion.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/05/Motorola-Edge-70-Fusion-Negro.png",
    "url": "https://altagamastore.ec/producto/moto-edge-70-fusion/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag44",
    "source": "alta-gama",
    "name": "Samsung Galaxy A37 5G",
    "specs": "Galaxy A37 5G",
    "price": 430.0,
    "image": "imagenes/124-galaxy-a37-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/06/Galaxy-A37-Negro.png",
    "url": "https://altagamastore.ec/producto/galaxy-a37-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag45",
    "source": "alta-gama",
    "name": "Xiaomi Poco X8 Pro 5G",
    "specs": "Poco X8 Pro 5G",
    "price": 440.0,
    "image": "imagenes/125-poco-x8-pro-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/03/POCO-X8-PRO-NEGRO1.png",
    "url": "https://altagamastore.ec/producto/poco-x8-pro-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag46",
    "source": "alta-gama",
    "name": "OPPO A6 PRO",
    "specs": "A6 PRO",
    "price": 440.0,
    "image": "imagenes/126-a6-pro.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/09/OPPO-A6-PRO-ROSA.png",
    "url": "https://altagamastore.ec/producto/a6-pro/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag47",
    "source": "alta-gama",
    "name": "Samsung Galaxy A56 5G",
    "specs": "Galaxy A56 5G",
    "price": 445.0,
    "image": "imagenes/127-galaxy-a56-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/IMG_6655.png",
    "url": "https://altagamastore.ec/producto/galaxy-a56/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag48",
    "source": "alta-gama",
    "name": "Google Pixel 9 – Open Box",
    "specs": "Pixel 9 – Open Box",
    "price": 450.0,
    "image": "imagenes/128-pixel-9-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-12-2.png",
    "url": "https://altagamastore.ec/producto/google-pixel-9/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag49",
    "source": "alta-gama",
    "name": "Honor 600e",
    "specs": "Honor 600e",
    "price": 450.0,
    "image": "imagenes/129-honor-600e.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/07/HONOR-600-E-DORADO.png",
    "url": "https://altagamastore.ec/producto/honor-600e/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag50",
    "source": "alta-gama",
    "name": "Apple iPhone 14 Plus – Open Box",
    "specs": "iPhone 14 Plus – Open Box",
    "price": 460.0,
    "image": "imagenes/130-iphone-14-plus-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-6-1.png",
    "url": "https://altagamastore.ec/producto/iphone-14-plus-openbox/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag51",
    "source": "alta-gama",
    "name": "Samsung Galaxy S22 Ultra – Open Box",
    "specs": "Galaxy S22 Ultra – Open Box",
    "price": 460.0,
    "image": "imagenes/131-galaxy-s22-ultra-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/S22-ULTRA-VERDE.png",
    "url": "https://altagamastore.ec/producto/open-box-samsung-galaxy-s22-ultra/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag52",
    "source": "alta-gama",
    "name": "Samsung Galaxy S24 – Open Box",
    "specs": "Galaxy S24 – Open Box",
    "price": 490.0,
    "image": "imagenes/132-galaxy-s24-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/11/S24-NEGRO.png",
    "url": "https://altagamastore.ec/producto/galaxy-s24-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag53",
    "source": "alta-gama",
    "name": "Samsung Galaxy S24 FE",
    "specs": "Galaxy S24 FE",
    "price": 500.0,
    "image": "imagenes/133-galaxy-s24-fe.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-1.png",
    "url": "https://altagamastore.ec/producto/galaxy-s24-fe-256gb-8gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag54",
    "source": "alta-gama",
    "name": "Xiaomi Redmi Note 15 Pro Plus 5G",
    "specs": "Redmi Note 15 Pro Plus 5G",
    "price": 500.0,
    "image": "imagenes/134-redmi-note-15-pro-plus-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/02/redmi-note-15-pro-cafe-moca.png",
    "url": "https://altagamastore.ec/producto/redmi-note-15-pro-plus-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag55",
    "source": "alta-gama",
    "name": "Samsung Galaxy A57 5G",
    "specs": "Galaxy A57 5G",
    "price": 500.0,
    "image": "imagenes/135-galaxy-a57-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/06/Galaxy-A57-Lila.png",
    "url": "https://altagamastore.ec/producto/galaxy-a57-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag56",
    "source": "alta-gama",
    "name": "Apple iPhone 13 Pro – Open Box",
    "specs": "iPhone 13 Pro – Open Box",
    "price": 510.0,
    "image": "imagenes/136-iphone-13-pro-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/02/iphone-13-pro-plata.png",
    "url": "https://altagamastore.ec/producto/iphone-13-pro-open-box-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag57",
    "source": "alta-gama",
    "name": "Motorola Edge 60 Pro",
    "specs": "Moto Edge 60 Pro",
    "price": 510.0,
    "image": "imagenes/137-moto-edge-60-pro.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/03/MOTO-EDGE-60-PRO-AZUL.png",
    "url": "https://altagamastore.ec/producto/moto-edge-60-pro/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag58",
    "source": "alta-gama",
    "name": "Apple iPhone 13",
    "specs": "iPhone 13",
    "price": 520.0,
    "image": "imagenes/138-iphone-13.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/IPHONE-13-ROJO.png",
    "url": "https://altagamastore.ec/producto/iphone-13/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag59",
    "source": "alta-gama",
    "name": "Apple iPhone 13 Pro Max – Open Box",
    "specs": "iPhone 13 Pro Max – Open Box",
    "price": 525.0,
    "image": "imagenes/139-iphone-13-pro-max-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/01/Mesa-de-trabajo-1-copia-58-1.png",
    "url": "https://altagamastore.ec/producto/open-box-iphone-13-pro-max/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag60",
    "source": "alta-gama",
    "name": "Samsung Galaxy S24 Plus – Open Box",
    "specs": "Galaxy S24 Plus – Open Box",
    "price": 535.0,
    "image": "imagenes/140-galaxy-s24-plus-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/02/IMG_2799.png",
    "url": "https://altagamastore.ec/producto/galaxy-s24/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag61",
    "source": "alta-gama",
    "name": "Samsung Galaxy S23 Ultra – Open Box",
    "specs": "Galaxy S23 Ultra – Open Box",
    "price": 550.0,
    "image": "imagenes/141-galaxy-s23-ultra-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/09/Galaxy-S23-Ultra-Negro.png",
    "url": "https://altagamastore.ec/producto/galaxy-s23-ultra-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag62",
    "source": "alta-gama",
    "name": "Samsung Galaxy S25 FE",
    "specs": "Galaxy S25 FE",
    "price": 550.0,
    "image": "imagenes/142-galaxy-s25-fe.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/10/Galaxy-S25-Fe-negro-azabache.png",
    "url": "https://altagamastore.ec/producto/galaxy-s25-fe/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag63",
    "source": "alta-gama",
    "name": "Apple iPhone 15 – Open Box",
    "specs": "iPhone 15 – Open Box",
    "price": 550.0,
    "image": "imagenes/143-iphone-15-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/02/iphone-15-celeste.png",
    "url": "https://altagamastore.ec/producto/iphone-15/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag64",
    "source": "alta-gama",
    "name": "Samsung Galaxy Z Flip 6 5G – Open Box",
    "specs": "Galaxy Z Flip 6 5G – Open Box",
    "price": 550.0,
    "image": "imagenes/144-galaxy-z-flip-6-5g-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/03/Galaxy-Z-Flip-6-Negro.png",
    "url": "https://altagamastore.ec/producto/galaxy-z-flip-6-5g-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag65",
    "source": "alta-gama",
    "name": "Xiaomi Poco X8 Pro Max 5G",
    "specs": "Poco X8 Pro Max 5G",
    "price": 560.0,
    "image": "imagenes/145-poco-x8-pro-max-5g.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/04/Poco-X8-Pro-Max-Negro.png",
    "url": "https://altagamastore.ec/producto/poco-x8-pro-max-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag66",
    "source": "alta-gama",
    "name": "Xiaomi Poco X8 Pro 5G Version Iron Man",
    "specs": "Poco X8 Pro 5G Version Iron Man",
    "price": 560.0,
    "image": "imagenes/146-poco-x8-pro-5g-version-iron-man.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/06/X8-PRO-VERSION-IRON-MAN.png",
    "url": "https://altagamastore.ec/producto/poco-x8-pro-5g-version-iron-man-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag67",
    "source": "alta-gama",
    "name": "Google Pixel 9A",
    "specs": "Pixel 9A",
    "price": 570.0,
    "image": "imagenes/147-pixel-9a.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2026/06/Pixel-9A-Negro.png",
    "url": "https://altagamastore.ec/producto/pixel-9a/",
    "badge": "Precio bajo"
  },
  {
    "id": "ag68",
    "source": "alta-gama",
    "name": "Apple iPhone 14 Pro – Open Box",
    "specs": "iPhone 14 Pro – Open Box",
    "price": 600.0,
    "image": "imagenes/148-iphone-14-pro-open-box.png",
    "image_remote": "https://altagamastore.ec/wp-content/uploads/2025/11/IPHONE-14-PRO-NEGRO.png",
    "url": "https://altagamastore.ec/producto/iphone-14-pro-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "t1",
    "source": "mundotek-tv",
    "name": "Box Xiaomi Mi Box S 3era Generacion 4K",
    "specs": "TV Box Xiaomi Mi Box S 3era Generacion 4K",
    "price": 89.0,
    "image": "imagenes/149-box-xiaomi-mi-box-s-3era-generacion-4k.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/06/tvbox2.webp",
    "url": "https://mundotek.com.ec/producto/tv-box-xiaomi-mi-box-s/",
    "badge": "#1 más económico"
  },
  {
    "id": "t2",
    "source": "mundotek-tv",
    "name": "House Tv HT-32 32 » hd led",
    "specs": "Smart tv House Tv HT-32 32 » hd led android 14 definición hd",
    "price": 135.0,
    "image": "imagenes/150-house-tv-ht-32-32-hd-led.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/07/hausetv.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-house-tv-ht-32-32-fhd-led-android-14-definicion-full-hd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t3",
    "source": "mundotek-tv",
    "name": "Philips ph 32gfs fisdb 32",
    "specs": "Smart tv Philips PH-32GFS-FISDB 32 » hd led android 14 google tv mando de voz sin bordes",
    "price": 155.0,
    "image": "imagenes/151-philips-ph-32gfs-fisdb-32.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/tv-philips32.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-philips-ph-32gfs-fisdb-32-hd-led-android-14-google-tv-mando-de-voz-sin-bordes/",
    "badge": "Precio bajo"
  },
  {
    "id": "t4",
    "source": "mundotek-tv",
    "name": "RCA 32 HDRC",
    "specs": "Televisor RCA 32 HDRC",
    "price": 155.0,
    "image": "imagenes/152-rca-32-hdrc.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/tvrca.webp",
    "url": "https://mundotek.com.ec/producto/televisor-rca-32-hdrc/",
    "badge": "Precio bajo"
  },
  {
    "id": "t5",
    "source": "mundotek-tv",
    "name": "Riviera RI-RLED – GLT32TPXM 32 » hd (1366×768) led hdr",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 159.0,
    "image": "imagenes/153-riviera-ri-rled-glt32tpxm-32-hd-1366-768-led-hdr.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/ri-rled-glt32tpxm.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-ri-rled-glt32tpxm-32-hd-1366x768-led-hdr-android-google-tv-mando-de-voz/",
    "badge": "Precio bajo"
  },
  {
    "id": "t6",
    "source": "mundotek-tv",
    "name": "Innova IN-LED-32HD-GTV-MP 32 » hd led",
    "specs": "Smart tv Innova IN-LED-32HD-GTV-MP 32 » hd led android google tv",
    "price": 159.0,
    "image": "imagenes/154-innova-in-led-32hd-gtv-mp-32-hd-led.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/in-led32hd-gtv-mp.jpg",
    "url": "https://mundotek.com.ec/producto/13477/",
    "badge": "Precio bajo"
  },
  {
    "id": "t7",
    "source": "mundotek-tv",
    "name": "Hisense 32Q4Q Qled sistema operativo Vida",
    "specs": "Tv Hisense 32Q4Q Qled sistema operativo Vida",
    "price": 169.0,
    "image": "imagenes/155-hisense-32q4q-qled-sistema-operativo-vida.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/hisense-serie-a4-smart-tv-a4q.png",
    "url": "https://mundotek.com.ec/producto/tv-hisense-32q4q-qled-sistema-operativo-vida/",
    "badge": "Precio bajo"
  },
  {
    "id": "t8",
    "source": "mundotek-tv",
    "name": "Motorola 32Tmkfhd",
    "specs": "Tv Motorola 32Tmkfhd GOOGLE TV 32PULGADAS",
    "price": 170.0,
    "image": "imagenes/156-motorola-32tmkfhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/03/32tmkgfhd.jpg",
    "url": "https://mundotek.com.ec/producto/tv-motorola-32tmkgfhd-android-11-32pulgadas/",
    "badge": "Precio bajo"
  },
  {
    "id": "t9",
    "source": "mundotek-tv",
    "name": "Google QLED Riviera",
    "specs": "Televisor Google QLED Riviera 32″ GLT32TPQ10",
    "price": 175.0,
    "image": "imagenes/157-google-qled-riviera.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/ri-rled-glt32tpq10.jpeg",
    "url": "https://mundotek.com.ec/producto/televisor-google-qled-riviera-32-glt32tpq10/",
    "badge": "Precio bajo"
  },
  {
    "id": "t10",
    "source": "mundotek-tv",
    "name": "Tcl 32S5K 32 » fhd qled",
    "specs": "Smart tv Tcl 32S5K 32 » fhd qled android 14 google tv",
    "price": 185.0,
    "image": "imagenes/158-tcl-32s5k-32-fhd-qled.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/s5k32.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-tcl-32s5k-32-fhd-qled-android-14-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t11",
    "source": "mundotek-tv",
    "name": "Google LED HD Indurama",
    "specs": "Televisor Google LED HD Indurama 32″ 32TIKGF5HD",
    "price": 185.0,
    "image": "imagenes/159-google-led-hd-indurama.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/32tikgf5hd.jpeg",
    "url": "https://mundotek.com.ec/producto/televisor-google-led-hd-indurama-32-32tikgf5hd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t12",
    "source": "mundotek-tv",
    "name": "HouseTV Televisor HouseTV",
    "specs": "HouseTV Televisor HouseTV 40″ Android 14",
    "price": 185.0,
    "image": "imagenes/160-housetv-televisor-housetv.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/tv40.png",
    "url": "https://mundotek.com.ec/producto/housetv-televisor-housetv-40-android-14/",
    "badge": "Precio bajo"
  },
  {
    "id": "t13",
    "source": "mundotek-tv",
    "name": "Lg 32lr650bpsa",
    "specs": "LG SMART TV 32» SMART TV con ThinQ AI 32LR650BPSA",
    "price": 199.0,
    "image": "https://mundotek.com.ec/wp-content/uploads/2025/01/32lr650bpsa.avif",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/32lr650bpsa.avif",
    "url": "https://mundotek.com.ec/producto/pantalla-lg-smart-tv-32-smart-tv-con-thinq-ai-32lr650bpsa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t14",
    "source": "mundotek-tv",
    "name": "House Tv HT-43 43 » fhd led",
    "specs": "Smart tv House Tv HT-43 43 » fhd led android 14 definición full hd",
    "price": 200.0,
    "image": "imagenes/162-house-tv-ht-43-43-fhd-led.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/07/hausetv.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-house-tv-ht-43-43-fhd-led-android-14-definicion-full-hd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t15",
    "source": "mundotek-tv",
    "name": "Rca 40fhdrc 40",
    "specs": "Tv Rca 40FHDRC 40 » fhd led google tv dolby audio bluetooth",
    "price": 215.0,
    "image": "imagenes/163-rca-40fhdrc-40.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/40fhdrc-full-hd.jpg",
    "url": "https://mundotek.com.ec/producto/tv-rca-40fhdrc-40-fhd-led-android-11-google-tv-dolby-audio-bluetooth/",
    "badge": "Precio bajo"
  },
  {
    "id": "t16",
    "source": "mundotek-tv",
    "name": "Motorola 43mknfhd/",
    "specs": "Televisor LED 43″ GOOGLE TV MOTOROLA 43MKNFHD",
    "price": 240.0,
    "image": "imagenes/164-motorola-43mknfhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/43mknfhd.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-led-43-google-tv-motorola-43mknfhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t17",
    "source": "mundotek-tv",
    "name": "Philips ph 43gfs fisdb 43",
    "specs": "Smart tv Philips PH-43GFS-FISDB 43 » fhd led android 14 mando",
    "price": 245.0,
    "image": "imagenes/165-philips-ph-43gfs-fisdb-43.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/philips-43-gfs-fisdb-1.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-philips-ph-43gfs-fisdb-43-fhd-led-android-14-mando-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "t18",
    "source": "mundotek-tv",
    "name": "43 Pulgadas TCL (43S5400)",
    "specs": "Tv 43 Pulgadas TCL (43S5400)",
    "price": 249.0,
    "image": "imagenes/166-43-pulgadas-tcl-43s5400.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/08/s5400-front-.jpg",
    "url": "https://mundotek.com.ec/producto/tv-32-pulgadas-tcl-43s5400/",
    "badge": "Precio bajo"
  },
  {
    "id": "t19",
    "source": "mundotek-tv",
    "name": "Innova in",
    "specs": "Smart tv Innova IN-LED-43FHD-GTV-MP 43 » fhd led android 14 google tv",
    "price": 249.0,
    "image": "imagenes/167-innova-in.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/12/tvled-43gfhd.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-innova-in-led-43fhd-gtv-mp-43-fhd-led-android-14-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t20",
    "source": "mundotek-tv",
    "name": "Hyundai FHD",
    "specs": "TV Hyundai FHD 43 pulgadas HYLED4326G Google TV",
    "price": 275.0,
    "image": "imagenes/168-hyundai-fhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/06/hyled4326g.jpg",
    "url": "https://mundotek.com.ec/producto/tv-hyundai-fhd-43-pulgadas-hyled4326g-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t21",
    "source": "mundotek-tv",
    "name": "Tcl 43S5K 43 » Qled",
    "specs": "TV Tcl 43S5K 43 » Qled android 14 google tv",
    "price": 275.0,
    "image": "imagenes/169-tcl-43s5k-43-qled.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/43s5k.jpg",
    "url": "https://mundotek.com.ec/producto/tv-tcl-43s5k-43-fhd-qled-android-14-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t22",
    "source": "mundotek-tv",
    "name": "Riviera ri rled glt43tpxm 43",
    "specs": "Smart tv Riviera RI-RLED-GLT43TPQ10 43 » QLED 43",
    "price": 289.0,
    "image": "imagenes/170-riviera-ri-rled-glt43tpxm-43.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/riviera-43.webp",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-ri-rled-glt43tpxm-43-fhd-1920x1080-led-hdr-android-google-tv-mando-de-voz/",
    "badge": "Precio bajo"
  },
  {
    "id": "t23",
    "source": "mundotek-tv",
    "name": "Tcl 43%e2%80%b3",
    "specs": "TV TCL 43″ 4K HDR GOOGLE TV (P635)",
    "price": 299.0,
    "image": "imagenes/171-tcl-43-e2-80-b3.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/11/Captura-de-pantalla_20221130_173941.png",
    "url": "https://mundotek.com.ec/producto/tv-tcl-43%e2%80%b3-4k-hdr-google-tv-p635/",
    "badge": "Precio bajo"
  },
  {
    "id": "t24",
    "source": "mundotek-tv",
    "name": "INDURAMA TV 43TIKJ5UHD",
    "specs": "SMART TV INDURAMA TV 43TIKJ5UHD 43Pulgadas",
    "price": 309.0,
    "image": "imagenes/172-indurama-tv-43tikj5uhd.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/02/tikhudhd.webp",
    "url": "https://mundotek.com.ec/producto/smart-tv-indurama-tv-43tikjuhd-43pulgadas/",
    "badge": "Precio bajo"
  },
  {
    "id": "t25",
    "source": "mundotek-tv",
    "name": "Lg 43pulgadas",
    "specs": "Televisor LG 43pulgadas UHD AI 43UA75 4K Smart TV 2025",
    "price": 325.0,
    "image": "imagenes/173-lg-43pulgadas.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/10/43ua75.webp",
    "url": "https://mundotek.com.ec/producto/televisor-lg-43pulgadas-uhd-ai-43ua75-4k-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t26",
    "source": "mundotek-tv",
    "name": "Samsung 50u8000",
    "specs": "Televisor Samsung LED 50″ Pulgadas Crystal UHD 4K 50U8000",
    "price": 339.0,
    "image": "imagenes/174-samsung-50u8000.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/televisor-samsung-led-50-pulgadas-mtk.webp",
    "url": "https://mundotek.com.ec/producto/televisor-samsung-led-50%e2%80%b3-pulgadas-crystal-uhd-4k-50u8000/",
    "badge": "Precio bajo"
  },
  {
    "id": "t27",
    "source": "mundotek-tv",
    "name": "Rca uhdrc",
    "specs": "Televisor RCA 50 Pulgadas UHDRC",
    "price": 340.0,
    "image": "imagenes/175-rca-uhdrc.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/50uhdrc.webp",
    "url": "https://mundotek.com.ec/producto/televisor-rca-50-pulgadas-uhdrc/",
    "badge": "Precio bajo"
  },
  {
    "id": "t28",
    "source": "mundotek-tv",
    "name": "Innova IN LED 50UHD GTV",
    "specs": "TV Innova IN LED 50UHD GTV 50″ GOOGLE TV",
    "price": 345.0,
    "image": "imagenes/176-innova-in-led-50uhd-gtv.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/50uhd.png",
    "url": "https://mundotek.com.ec/producto/tv-innova-in-led-50uhd-gtv-50-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t29",
    "source": "mundotek-tv",
    "name": "RIVIERA QLED 4K -GLT50TPQ10",
    "specs": "TV RIVIERA QLED 4K -GLT50TPQ10 50″ GOOGLE TV",
    "price": 369.0,
    "image": "imagenes/177-riviera-qled-4k--glt50tpq10.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/rled-glt50tpq10.png",
    "url": "https://mundotek.com.ec/producto/tv-riviera-qled-4k-glt50tpq10-50%e2%80%b3-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t30",
    "source": "mundotek-tv",
    "name": "Crystal UHD DU7000 4K de 50” con sistema operativo Tizen",
    "specs": "Televisor inteligente Crystal UHD DU7000 4K de 50” con sistema operativo Tizen",
    "price": 369.0,
    "image": "imagenes/178-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/du7000-mtk.webp",
    "url": "https://mundotek.com.ec/producto/televisor-inteligente-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen-oferta-de-verano/",
    "badge": "Precio bajo"
  },
  {
    "id": "t31",
    "source": "mundotek-tv",
    "name": "Indurama LED 4K50 Pulgadas (50TIKGF2GUHD",
    "specs": "Tv Indurama LED 4K50 Pulgadas (50TIKGF2GUHD Google Tv)",
    "price": 379.0,
    "image": "imagenes/179-indurama-led-4k50-pulgadas-50tikgf2guhd.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/10/d_nq_np_783527-mec53271187298_012023-o.webp",
    "url": "https://mundotek.com.ec/producto/tv-indurama-qled-50-pulgadas-50tikgf2guhd-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t32",
    "source": "mundotek-tv",
    "name": "Innova in",
    "specs": "Smart tv Innova IN-LED-55UHD-GTV-MP 55 » 4k uhd led",
    "price": 379.0,
    "image": "imagenes/180-innova-in.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/12/in-led55mtk.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-innova-in-led-55uhd-gtv-mp-55-4k-uhd-led/",
    "badge": "Precio bajo"
  },
  {
    "id": "t33",
    "source": "mundotek-tv",
    "name": "Riviera rled glt55tpx9 55",
    "specs": "Smart tv Riviera RLED-GLT55PX9 55 » 4k uhd led android google tv color negro 2025",
    "price": 399.0,
    "image": "imagenes/181-riviera-rled-glt55tpx9-55.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/google-tv-glt55px9.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-rled-glt55tpx9-55-4k-uhd-led-android-google-tv-color-negro/",
    "badge": "Precio bajo"
  },
  {
    "id": "t34",
    "source": "mundotek-tv",
    "name": "LG UHD AI 50UA7500 4K",
    "specs": "Televisor LG UHD AI 50UA7500 4K Smart TV",
    "price": 409.0,
    "image": "imagenes/182-lg-uhd-ai-50ua7500-4k.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/50ua7500.jpeg",
    "url": "https://mundotek.com.ec/producto/televisor-lg-uhd-ai-50ua7500-4k-smart-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t35",
    "source": "mundotek-tv",
    "name": "Tcl v6c televisor",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 415.0,
    "image": "imagenes/183-tcl-v6c-televisor.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/02/tcl_55v6cuk_mtk.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-led-55-pulgadas-tcl-v6c-televisor-4k-hdr-smart-tv-con-tecnologia-de-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t36",
    "source": "mundotek-tv",
    "name": "Hisense 55%e2%80%b3",
    "specs": "Tv Hisense 55″ LED 4K Smart VIDAA 55A6H",
    "price": 419.0,
    "image": "imagenes/184-hisense-55-e2-80-b3.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/05/tv-hisense-55-55a6h.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-tv-hisense-55%e2%80%b3-led-4k-smart-vidaa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t37",
    "source": "mundotek-tv",
    "name": "Hisense 55Q6QV 55 » 4k uhd QLED Vidaa",
    "specs": "Televisor Hisense 55Q6QV 55 » 4k uhd QLED Vidaa",
    "price": 419.0,
    "image": "imagenes/185-hisense-55q6qv-55-4k-uhd-qled-vidaa.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/55q6qv.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-hisense-55q6qv-55-4k-uhd-qled-vidaa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t38",
    "source": "mundotek-tv",
    "name": "Riviera QLED",
    "specs": "Televisor Riviera QLED 55″ RLED-GLT55TPQ10",
    "price": 429.0,
    "image": "imagenes/186-riviera-qled.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/rled-glt55tpq10.webp",
    "url": "https://mundotek.com.ec/producto/televisor-riviera-qled-55-rled-glt55tpq10/",
    "badge": "Precio bajo"
  },
  {
    "id": "t39",
    "source": "mundotek-tv",
    "name": "Motorola 55MGFUHD Google 4K Tv",
    "specs": "Televisor Motorola 55MGFUHD Google 4K Tv 55″",
    "price": 439.0,
    "image": "imagenes/187-motorola-55mgfuhd-google-4k-tv.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/mtk-tmkuhd.png",
    "url": "https://mundotek.com.ec/producto/televisor-motorola-55tmkuhd-google-tv-55/",
    "badge": "Precio bajo"
  },
  {
    "id": "t40",
    "source": "mundotek-tv",
    "name": "PHILIPS QLED",
    "specs": "Televisor PHILIPS QLED 55″ Pulgadas UHD 4K – Google TV – Q55gfu",
    "price": 439.0,
    "image": "imagenes/188-philips-qled.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/55gfu.png",
    "url": "https://mundotek.com.ec/producto/televisor-philips-qled-55%e2%80%b3-pulgadas-uhd-4k-google-tv-q55gfu/",
    "badge": "Precio bajo"
  },
  {
    "id": "t41",
    "source": "mundotek-tv",
    "name": "Crystal UHD DU7000 4K de 50” con sistema operativo Tizen",
    "specs": "Televisor inteligente Crystal UHD DU7000 4K de 50” con sistema operativo Tizen",
    "price": 459.0,
    "image": "imagenes/189-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/du7000-mtk.webp",
    "url": "https://mundotek.com.ec/producto/televisor-inteligente-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen-2024-copia/",
    "badge": "Precio bajo"
  },
  {
    "id": "t42",
    "source": "mundotek-tv",
    "name": "Qled TCL 55T6C",
    "specs": "Televisor Qled TCL 55T6C 55 PULGADAS",
    "price": 469.0,
    "image": "imagenes/190-qled-tcl-55t6c.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/qled-tcl-t6c.webp",
    "url": "https://mundotek.com.ec/producto/televisor-qled-tcl-t6c-55-pulgadas/",
    "badge": "Precio bajo"
  },
  {
    "id": "t43",
    "source": "mundotek-tv",
    "name": "Samsung 50q7faa",
    "specs": "Samsung 50 pulgadas 50Q7FAA Series 4K Vision AI Smart TV",
    "price": 489.0,
    "image": "https://mundotek.com.ec/wp-content/uploads/2026/04/q7faa-50.avif",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/q7faa-50.avif",
    "url": "https://mundotek.com.ec/producto/samsung-50-pulgadas-50q7faa-series-4k-vision-ai-smart-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t44",
    "source": "mundotek-tv",
    "name": "55″ Crystal UHD 4K 55U8000 Tizen OS",
    "specs": "TV 55″ Crystal UHD 4K 55U8000 Tizen OS Smart TV (2026)",
    "price": 499.0,
    "image": "imagenes/192-55-crystal-uhd-4k-55u8000-tizen-os.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/ue65u8000.png",
    "url": "https://mundotek.com.ec/producto/tv-55-crystal-uhd-4k-u8000-tizen-os-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t45",
    "source": "mundotek-tv",
    "name": "INNOVA IN-TVLED-65GUHD-MP",
    "specs": "TELEVISOR INNOVA IN-TVLED-65GUHD-MP GOOGLE TV 65″",
    "price": 519.0,
    "image": "https://mundotek.com.ec/wp-content/uploads/2026/04/tv65.avif",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/tv65.avif",
    "url": "https://mundotek.com.ec/producto/televisor-innova-in-tvled-65guhd-mp-google-tv-65/",
    "badge": "Precio bajo"
  },
  {
    "id": "t46",
    "source": "mundotek-tv",
    "name": "Philips Led 65GFS-FISDB",
    "specs": "Televisor Philips Led 65GFS-FISDB Google Tv 65″",
    "price": 525.0,
    "image": "imagenes/194-philips-led-65gfs-fisdb.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/philips-65-gfs-fisdb.png",
    "url": "https://mundotek.com.ec/producto/televisor-philips-led-65gfs-fisdb-google-tv-65/",
    "badge": "Precio bajo"
  },
  {
    "id": "t47",
    "source": "mundotek-tv",
    "name": "55″ LG UHD AI 4K",
    "specs": "55″ LG UHD AI 4K Smart TV 55ua7300 2025",
    "price": 530.0,
    "image": "imagenes/195-55-lg-uhd-ai-4k.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/10/65ua73.webp",
    "url": "https://mundotek.com.ec/producto/55-lg-uhd-ai-4k-smart-tv-55ua7300-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t48",
    "source": "mundotek-tv",
    "name": "Samsung 55 mini",
    "specs": "Televisor Samsung 55″ Mini LED UHD UN55M70HAGXPE",
    "price": 539.0,
    "image": "imagenes/196-samsung-55-mini.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/nini-led-sam.webp",
    "url": "https://mundotek.com.ec/producto/televisor-samsung-55-mini-led-uhd-un55m70hagxpe/",
    "badge": "Precio bajo"
  },
  {
    "id": "t49",
    "source": "mundotek-tv",
    "name": "Lg 60",
    "specs": "Televisor LG 60″ LED 4K UHD 60UA8500PSA",
    "price": 549.0,
    "image": "imagenes/197-lg-60.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/60ua85.webp",
    "url": "https://mundotek.com.ec/producto/televisor-lg-60-led-4k-uhd-60ua8500psa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t50",
    "source": "mundotek-tv",
    "name": "Pantalla LG NanoCell 55» NANO80TSA 4K",
    "specs": "Pantalla LG NanoCell 55» NANO80TSA 4K SMART TV con ThinQ AI",
    "price": 555.0,
    "image": "imagenes/198-pantalla-lg-nanocell-55-nano80tsa-4k.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/09/55nano77.webp",
    "url": "https://mundotek.com.ec/producto/pantalla-lg-nanocell-55-nano77-4k-smart-tv-con-thinq-ai/",
    "badge": "Precio bajo"
  },
  {
    "id": "t51",
    "source": "mundotek-tv",
    "name": "Motorola 65",
    "specs": "Televisor Motorola 65″ LED 4K UHD 65MNUHD",
    "price": 559.0,
    "image": "imagenes/199-motorola-65.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/65mnuhd.webp",
    "url": "https://mundotek.com.ec/producto/televisor-motorola-65-led-4k-uhd-65mnuhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t52",
    "source": "mundotek-tv",
    "name": "Riviera glt65px9 65",
    "specs": "Smart tv Riviera GLT65PX9 65 » 4k uhd led android google tv sin borde mando de voz 2025",
    "price": 569.0,
    "image": "imagenes/200-riviera-glt65px9-65.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/tv-glt65px9.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-glt65px9-65-4k-uhd-led-android-google-tv-sin-borde-mando-de-voz-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t53",
    "source": "mundotek-tv",
    "name": "65″ INDURAMA UHD",
    "specs": "Televisor 65″ INDURAMA UHD Google Tv TIKGF2GUHD",
    "price": 580.0,
    "image": "imagenes/201-65-indurama-uhd.png",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/65-tikgf2gudh-4k-google-tv.png",
    "url": "https://mundotek.com.ec/producto/televisor-65-indurama-uhd-google-tv-tikgf2guhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t54",
    "source": "mundotek-tv",
    "name": "Samsung vision ai",
    "specs": "Tv Samsung 55″ QLED Q7FAA 4K Vision AI Smart TV (2025)",
    "price": 589.0,
    "image": "imagenes/202-samsung-vision-ai.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/tv.webp",
    "url": "https://mundotek.com.ec/producto/55-qled-q7f-4k-samsung-vision-ai-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t55",
    "source": "mundotek-tv",
    "name": "65Pulgadas TCL P6K 4K UHD",
    "specs": "Televisor 65Pulgadas TCL P6K 4K UHD",
    "price": 599.0,
    "image": "imagenes/203-65pulgadas-tcl-p6k-4k-uhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/p6k.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-65pulgadas-tcl-p6k-4k-uhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t56",
    "source": "mundotek-tv",
    "name": "Hisense Hi-QLED MiniLED",
    "specs": "TV Hisense Hi-QLED MiniLED 55″ 4K 55U6ESG Google TV 2026",
    "price": 599.0,
    "image": "imagenes/204-hisense-hi-qled-miniled.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/50u6esg.webp",
    "url": "https://mundotek.com.ec/producto/tv-hisense-hi-qled-miniled-55-4k-55u6esg-google-tv-2026/",
    "badge": "Precio bajo"
  },
  {
    "id": "t57",
    "source": "mundotek-tv",
    "name": "Tcl 55 p8l premium",
    "specs": "Televisor TCL 55″ P8L Premium QLED QD-Mini LED TV 2026",
    "price": 610.0,
    "image": "imagenes/205-tcl-55-p8l-premium.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/p8l-55.webp",
    "url": "https://mundotek.com.ec/producto/televisor-tcl-55-p8l-premium-qled-tv-2026/",
    "badge": "Precio bajo"
  }
];
